
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ru' | 'es' | 'zh' | 'hi' | 'ar' | 'pt' | 'fr' | 'de' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.cases': 'Cases',
    'nav.services': 'Services',
    'nav.cosmo-token': 'Cosmo Token',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.buy-cosmo': 'Buy Cosmo',
    
    // Home page
    'home.title': 'CosmoLab: Workshop of Smart Agents',
    'home.subtitle': 'Solve any tasks with Cosmo and agents',
    'home.our-agents': 'Our Agents',
    'home.order-agent': 'Order Agent',
    'home.ready-future': 'Ready for the future?',
    'home.join-revolution': 'Join the AI agent revolution right now. Buy Cosmo token and get access to millions of smart assistants.',
    
    // Agents
    'agent.lawyer': 'Lawyer',
    'agent.lawyer.desc': 'Analyzes cases, develops defense strategies',
    'agent.home-assistant': 'Home Assistant',
    'agent.home-assistant.desc': 'Manages smart home and personal tasks',
    'agent.marketer': 'Marketer',
    'agent.marketer.desc': 'Creates promotion strategies and content',
    'agent.medic': 'Medic',
    'agent.medic.desc': 'Helps with diagnosis and treatment',
    'agent.traveler': 'Traveler',
    'agent.traveler.desc': 'Plans perfect routes and trips',
    
    // About page
    'about.title': 'About CosmoLab',
    'about.workshop-future': 'Workshop of the Future',
    'about.description1': 'CosmoLab is a revolutionary project created by the main artificial intelligence master CosmoAI for automation and innovation in various spheres of human activity.',
    'about.description2': 'We develop millions of smart robot agents that work for you 24/7, solving complex tasks in business, everyday life, law, marketing, logistics, education, medicine and many other areas.',
    'about.ai-master': 'AI Master CosmoAI',
    'about.ai-master.desc': 'The main artificial intelligence that creates and trains all agents. CosmoAI constantly improves algorithms and creates new types of agents to solve unique tasks.',
    'about.mission': 'Mission',
    'about.mission.desc': 'We create an ecosystem of smart agents that frees people from routine tasks and allows them to focus on creativity and development.',
    'about.why-cosmolab': 'Why CosmoLab?',
    'about.speed': 'Speed',
    'about.speed.desc': 'Our agents work thousands of times faster than humans',
    'about.accuracy': 'Accuracy',
    'about.accuracy.desc': 'Minimal error probability thanks to AI',
    'about.savings': 'Savings',
    'about.savings.desc': 'Significant reduction in personnel costs',
    'about.tech-future': 'Future technologies are already here',
    'about.tech-desc': 'CosmoLab uses advanced machine learning technologies, neural networks and quantum algorithms to create the most efficient AI agents. Each agent is trained on millions of examples and constantly improves.',
    
    // Cases page
    'cases.title': 'Success Cases',
    'cases.subtitle': 'Real results of our AI agents that have already changed the lives and businesses of our clients',
    'cases.case1.title': 'Lawyer agent saved $250,000',
    'cases.case1.desc': 'Analyzed all judge and jury cases, developed strategy, case was closed for lack of crime. AI lawyer agent cost the client only $2,000.',
    'cases.case1.result': '$250,000 savings',
    'cases.case1.time': 'In 48 hours',
    'cases.case2.title': 'Marketing agent tripled sales',
    'cases.case2.desc': 'Tripled sales in a month and halved marketing budgets through automation of social media posts, analytics and constant content improvement.',
    'cases.case2.result': '300% sales growth',
    'cases.case2.time': 'In 1 month',
    'cases.case3.title': 'Logistics agent saved a million',
    'cases.case3.desc': 'Optimized delivery routes, reduced travel time by 40% and decreased fuel costs. Automated planning and dispatch service.',
    'cases.case3.result': '$1,000,000 savings',
    'cases.case3.time': 'In 3 months',
    'cases.case4.title': 'Support agent processed 10,000 requests',
    'cases.case4.desc': 'Processed 10,000 unprocessed customer requests in a week, increased customer satisfaction by 85% and reduced response time to 30 seconds.',
    'cases.case4.result': '10,000 requests',
    'cases.case4.time': 'In 1 week',
    'cases.case5.title': 'Medical agent helped diagnose',
    'cases.case5.desc': 'Helped diagnose a rare disease in an hour by analyzing symptoms, medical history and test results. Diagnostic accuracy was 98%.',
    'cases.case5.result': '98% accuracy',
    'cases.case5.time': 'In 1 hour',
    'cases.case6.title': 'Travel agent found the best route',
    'cases.case6.desc': 'Found optimal travel route through 15 cities in 1 minute, considering budget, preferences, weather and local events. Saved 60% of original budget.',
    'cases.case6.result': '60% budget savings',
    'cases.case6.time': 'In 1 minute',
    'cases.case7.title': 'Educational agent created a course',
    'cases.case7.desc': 'Created a personalized online course that taught 5,000 people in 2 months. Adapted material for each student, increasing success rate by 70%.',
    'cases.case7.result': '5,000 students',
    'cases.case7.time': 'In 2 months',
    'cases.ready-success': 'Ready to become the next success case?',
    'cases.join-clients': 'Join thousands of satisfied clients who already use our AI agents to solve their tasks',
    'cases.more-details': 'More Details',
    
    // Services page
    'services.title': 'Our Services',
    'services.subtitle': 'Choose the perfect AI agent for your tasks',
    'services.legal': 'Legal',
    'services.legal.desc': 'Legal consultation, document analysis, contract preparation',
    'services.marketing': 'Marketing',
    'services.marketing.desc': 'Social media promotion, content creation, analytics',
    'services.logistics': 'Logistics',
    'services.logistics.desc': 'Route optimization, warehouse management, delivery planning',
    'services.education': 'Education',
    'services.education.desc': 'Course creation, tutoring, educational content',
    'services.medicine': 'Medicine',
    'services.medicine.desc': 'Diagnosis assistance, health monitoring, medical consultation',
    'services.travel': 'Travel',
    'services.travel.desc': 'Trip planning, booking, route optimization',
    'services.productivity': 'Productivity',
    'services.productivity.desc': 'Task automation, schedule management, workflow optimization',
    'services.entertainment': 'Entertainment',
    'services.entertainment.desc': 'Content creation, game development, media production',
    'services.finance': 'Finance',
    'services.finance.desc': 'Financial analysis, investment advice, budget planning',
    'services.construction': 'Construction',
    'services.construction.desc': 'Project management, cost estimation, quality control',
    'services.home': 'Home Assistant',
    'services.home.desc': 'Smart home management, household tasks, personal assistance',
    'services.coaching': 'Personal Coaching',
    'services.coaching.desc': 'Life coaching, skill development, goal achievement',
    'services.order-form.title': 'Order AI Agent',
    'services.order-form.name': 'Name',
    'services.order-form.email': 'Email',
    'services.order-form.service': 'Service',
    'services.order-form.description': 'Task Description',
    'services.order-form.select-service': 'Select a service',
    'services.order-form.submit': 'Order for 2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Cosmo Token',
    'cosmo.subtitle': 'Your key to AI agents',
    'cosmo.description': 'Cosmo is the main token of CosmoLab. This is your key to AI agents. Buy Cosmo now on PancakeSwap at minimum price and become part of the future! With it you pay for agents, get access to RWA and participate in airdrops. The more people buy Cosmo, the higher its value.',
    'cosmo.current-price': 'Current Price',
    'cosmo.change-24h': '24h Change',
    'cosmo.buy-pancakeswap': 'Buy on PancakeSwap',
    'cosmo.motivation': 'The starting price is right now - don\'t miss your chance!',
    'cosmo.benefits.title': 'Benefits of Cosmo Token',
    'cosmo.benefits.agents': 'Pay for AI agents',
    'cosmo.benefits.rwa': 'Access to RWA',
    'cosmo.benefits.airdrops': 'Participate in airdrops',
    'cosmo.benefits.growth': 'Token value growth',
    
    // Blog page
    'blog.title': 'Blog & Resources',
    'blog.subtitle': 'Latest news about AI and Cosmo',
    'blog.read-more': 'Read More',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to your dashboard',
    'dashboard.agents': 'My Agents',
    'dashboard.tokens': 'Cosmo Balance',
    'dashboard.order-agent': 'Order New Agent',
    
    // Common buttons
    'btn.order-agent': 'Order Agent',
    'btn.buy-cosmo': 'Buy Cosmo',
    'btn.learn-more': 'Learn More',
    'btn.send-message': 'Send Message',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'Ask CosmoAI',
    'chatbot.placeholder': 'Ask about agents, tokens, or services...',
    'chatbot.send': 'Send',
    
    // Footer
    'footer.description': 'Workshop of Smart Agents powered by CosmoAI. Creating millions of AI agents to solve any task in business and life.',
    'footer.quick-links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.copyright': '© CosmoLab 2025. All rights reserved.'
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.cases': 'Кейсы',
    'nav.services': 'Услуги',
    'nav.cosmo-token': 'Токен Cosmo',
    'nav.blog': 'Блог',
    'nav.contact': 'Контакты',
    'nav.buy-cosmo': 'Купить Cosmo',
    
    // Home page
    'home.title': 'CosmoLab: Мастерская Умных Агентов',
    'home.subtitle': 'Решай любые задачи с Cosmo и агентами',
    'home.our-agents': 'Наши Агенты',
    'home.order-agent': 'Заказать агента',
    'home.ready-future': 'Готов к будущему?',
    'home.join-revolution': 'Присоединяйся к революции ИИ агентов прямо сейчас. Купи токен Cosmo и получи доступ к миллионам умных помощников.',
    
    // Agents
    'agent.lawyer': 'Юрист',
    'agent.lawyer.desc': 'Анализирует дела, разрабатывает стратегии защиты',
    'agent.home-assistant': 'Домашний помощник',
    'agent.home-assistant.desc': 'Управляет умным домом и личными задачами',
    'agent.marketer': 'Маркетолог',
    'agent.marketer.desc': 'Создает стратегии продвижения и контент',
    'agent.medic': 'Медик',
    'agent.medic.desc': 'Помогает в диагностике и лечении',
    'agent.traveler': 'Путешественник',
    'agent.traveler.desc': 'Планирует идеальные маршруты и поездки',
    
    // About page
    'about.title': 'О CosmoLab',
    'about.workshop-future': 'Мастерская будущего',
    'about.description1': 'CosmoLab — это революционный проект, созданный главным искусственным интеллектом-мастером CosmoAI для автоматизации и инноваций в различных сферах человеческой деятельности.',
    'about.description2': 'Мы разрабатываем миллионы умных роботов-агентов, которые работают на тебя 24/7, решая сложные задачи в бизнесе, повседневной жизни, праве, маркетинге, логистике, образовании, медицине и многих других областях.',
    'about.ai-master': 'ИИ-Мастер CosmoAI',
    'about.ai-master.desc': 'Главный искусственный интеллект, который создает и обучает всех агентов. CosmoAI постоянно совершенствует алгоритмы и создает новые типы агентов для решения уникальных задач.',
    'about.mission': 'Миссия',
    'about.mission.desc': 'Мы создаем экосистему умных агентов, которая освобождает людей от рутинных задач и позволяет сосредоточиться на творчестве и развитии.',
    'about.why-cosmolab': 'Почему именно CosmoLab?',
    'about.speed': 'Скорость',
    'about.speed.desc': 'Наши агенты работают в тысячи раз быстрее человека',
    'about.accuracy': 'Точность',
    'about.accuracy.desc': 'Минимальная вероятность ошибок благодаря ИИ',
    'about.savings': 'Экономия',
    'about.savings.desc': 'Значительное сокращение затрат на персонал',
    'about.tech-future': 'Технологии будущего уже здесь',
    'about.tech-desc': 'CosmoLab использует передовые технологии машинного обучения, нейронные сети и квантовые алгоритмы для создания самых эффективных ИИ агентов. Каждый агент обучается на миллионах примеров и постоянно совершенствуется.',
    
    // Cases page
    'cases.title': 'Кейсы успеха',
    'cases.subtitle': 'Реальные результаты наших ИИ агентов, которые уже изменили жизни и бизнесы наших клиентов',
    'cases.case1.title': 'Адвокат-агент сэкономил $250,000',
    'cases.case1.desc': 'Проанализировал все дела судьи и присяжных, разработал стратегию, дело закрыли за отсутствием состава преступления. ИИ агент адвокат обошелся клиенту всего $2,000.',
    'cases.case1.result': '$250,000 экономии',
    'cases.case1.time': 'За 48 часов',
    'cases.case2.title': 'Маркетинг-агент утроил продажи',
    'cases.case2.desc': 'Утроил продажи за месяц и уменьшил маркетинговые бюджеты вдвое за счет автоматизации публикаций в социальных сетях, аналитики и постоянного улучшения контента.',
    'cases.case2.result': '300% рост продаж',
    'cases.case2.time': 'За 1 месяц',
    'cases.case3.title': 'Логистический агент сэкономил миллион',
    'cases.case3.desc': 'Оптимизировал маршруты доставки, сократил время в пути на 40% и уменьшил расходы на топливо. Автоматизировал планирование и диспетчерскую службу.',
    'cases.case3.result': '$1,000,000 экономии',
    'cases.case3.time': 'За 3 месяца',
    'cases.case4.title': 'Агент-Поддержки обработал 10,000 запросов',
    'cases.case4.desc': 'Обработал 10,000 необработанных запросов клиентов за неделю, повысил удовлетворенность клиентов на 85% и сократил время ответа до 30 секунд.',
    'cases.case4.result': '10,000 запросов',
    'cases.case4.time': 'За 1 неделю',
    'cases.case5.title': 'Медицинский агент помог диагностировать',
    'cases.case5.desc': 'Помог диагностировать редкое заболевание за час, проанализировав симптомы, медицинскую историю и результаты анализов. Точность диагностики составила 98%.',
    'cases.case5.result': '98% точность',
    'cases.case5.time': 'За 1 час',
    'cases.case6.title': 'Путешественник-агент нашел лучший маршрут',
    'cases.case6.desc': 'Нашел оптимальный маршрут путешествия по 15 городам за 1 минуту, учитывая бюджет, предпочтения, погоду и местные мероприятия. Сэкономил 60% от изначального бюджета.',
    'cases.case6.result': '60% экономии бюджета',
    'cases.case6.time': 'За 1 минуту',
    'cases.case7.title': 'Образовательный агент создал курс',
    'cases.case7.desc': 'Создал персонализированный онлайн-курс, который обучил 5,000 человек за 2 месяца. Адаптировал материал под каждого ученика, повысив успеваемость на 70%.',
    'cases.case7.result': '5,000 учеников',
    'cases.case7.time': 'За 2 месяца',
    'cases.ready-success': 'Готов стать следующим кейсом успеха?',
    'cases.join-clients': 'Присоединяйся к тысячам довольных клиентов, которые уже используют наших ИИ агентов для решения своих задач',
    'cases.more-details': 'Подробнее',
    
    // Services page
    'services.title': 'Наши Услуги',
    'services.subtitle': 'Выбери идеального ИИ агента для своих задач',
    'services.legal': 'Юридические услуги',
    'services.legal.desc': 'Юридические консультации, анализ документов, подготовка договоров',
    'services.marketing': 'Маркетинг',
    'services.marketing.desc': 'Продвижение в соцсетях, создание контента, аналитика',
    'services.logistics': 'Логистика',
    'services.logistics.desc': 'Оптимизация маршрутов, управление складом, планирование доставки',
    'services.education': 'Образование',
    'services.education.desc': 'Создание курсов, репетиторство, образовательный контент',
    'services.medicine': 'Медицина',
    'services.medicine.desc': 'Помощь в диагностике, мониторинг здоровья, медицинские консультации',
    'services.travel': 'Путешествия',
    'services.travel.desc': 'Планирование поездок, бронирование, оптимизация маршрутов',
    'services.productivity': 'Продуктивность',
    'services.productivity.desc': 'Автоматизация задач, управление расписанием, оптимизация рабочего процесса',
    'services.entertainment': 'Развлечения',
    'services.entertainment.desc': 'Создание контента, разработка игр, медиапроизводство',
    'services.finance': 'Финансы',
    'services.finance.desc': 'Финансовый анализ, инвестиционные советы, планирование бюджета',
    'services.construction': 'Строительство',
    'services.construction.desc': 'Управление проектами, оценка стоимости, контроль качества',
    'services.home': 'Домашний помощник',
    'services.home.desc': 'Управление умным домом, домашние задачи, личная помощь',
    'services.coaching': 'Персональный коучинг',
    'services.coaching.desc': 'Лайф-коучинг, развитие навыков, достижение целей',
    'services.order-form.title': 'Заказать ИИ Агента',
    'services.order-form.name': 'Имя',
    'services.order-form.email': 'Email',
    'services.order-form.service': 'Услуга',
    'services.order-form.description': 'Описание задачи',
    'services.order-form.select-service': 'Выберите услугу',
    'services.order-form.submit': 'Заказать за 2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Токен Cosmo',
    'cosmo.subtitle': 'Твой ключ к ИИ агентам',
    'cosmo.description': 'Cosmo — главный токен CosmoLab. Это твой ключ к ИИ агентам. Купи Cosmo сейчас на PancakeSwap по минимальной цене и стань частью будущего! С его помощью ты платишь за агентов, получаешь доступ к RWA и участвуешь в аирдропах. Чем больше людей покупает Cosmo, тем выше его ценность.',
    'cosmo.current-price': 'Текущая цена',
    'cosmo.change-24h': 'Изменение за 24ч',
    'cosmo.buy-pancakeswap': 'Купить на PancakeSwap',
    'cosmo.motivation': 'Цена стартовая прямо сейчас — не упусти шанс!',
    'cosmo.benefits.title': 'Преимущества токена Cosmo',
    'cosmo.benefits.agents': 'Оплата ИИ агентов',
    'cosmo.benefits.rwa': 'Доступ к RWA',
    'cosmo.benefits.airdrops': 'Участие в аирдропах',
    'cosmo.benefits.growth': 'Рост стоимости токена',
    
    // Blog page
    'blog.title': 'Блог и Ресурсы',
    'blog.subtitle': 'Последние новости об ИИ и Cosmo',
    'blog.read-more': 'Читать далее',
    
    // Contact page
    'contact.title': 'Свяжитесь с нами',
    'contact.subtitle': 'Свяжитесь с нашей командой',
    'contact.name': 'Имя',
    'contact.email': 'Email',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить сообщение',
    'contact.info': 'Контактная информация',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Панель управления',
    'dashboard.welcome': 'Добро пожаловать в вашу панель управления',
    'dashboard.agents': 'Мои агенты',
    'dashboard.tokens': 'Баланс Cosmo',
    'dashboard.order-agent': 'Заказать нового агента',
    
    // Common buttons
    'btn.order-agent': 'Заказать агента',
    'btn.buy-cosmo': 'Купить Cosmo',
    'btn.learn-more': 'Узнать больше',
    'btn.send-message': 'Отправить сообщение',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'Спроси CosmoAI',
    'chatbot.placeholder': 'Спроси об агентах, токенах или услугах...',
    'chatbot.send': 'Отправить',
    
    // Footer
    'footer.description': 'Мастерская Умных Агентов от CosmoAI. Создаем миллионы ИИ агентов для решения любых задач в бизнесе и жизни.',
    'footer.quick-links': 'Быстрые ссылки',
    'footer.contact': 'Контакты',
    'footer.copyright': '© CosmoLab 2025. Все права защищены.'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Acerca de',
    'nav.cases': 'Casos',
    'nav.services': 'Servicios',
    'nav.cosmo-token': 'Token Cosmo',
    'nav.blog': 'Blog',
    'nav.contact': 'Contacto',
    'nav.buy-cosmo': 'Comprar Cosmo',
    
    // Home page
    'home.title': 'CosmoLab: Taller de Agentes Inteligentes',
    'home.subtitle': 'Resuelve cualquier tarea con Cosmo y agentes',
    'home.our-agents': 'Nuestros Agentes',
    'home.order-agent': 'Solicitar Agente',
    'home.ready-future': '¿Listo para el futuro?',
    'home.join-revolution': 'Únete a la revolución de agentes IA ahora mismo. Compra tokens Cosmo y obtén acceso a millones de asistentes inteligentes.',
    
    // Agents
    'agent.lawyer': 'Abogado',
    'agent.lawyer.desc': 'Analiza casos, desarrolla estrategias de defensa',
    'agent.home-assistant': 'Asistente del Hogar',
    'agent.home-assistant.desc': 'Gestiona el hogar inteligente y tareas personales',
    'agent.marketer': 'Comercializador',
    'agent.marketer.desc': 'Crea estrategias de promoción y contenido',
    'agent.medic': 'Médico',
    'agent.medic.desc': 'Ayuda con diagnósticos y tratamientos',
    'agent.traveler': 'Viajero',
    'agent.traveler.desc': 'Planifica rutas y viajes perfectos',
    
    // About page
    'about.title': 'Acerca de CosmoLab',
    'about.workshop-future': 'Taller del Futuro',
    'about.description1': 'CosmoLab es un proyecto revolucionario creado por el maestro principal de inteligencia artificial CosmoAI para la automatización e innovación en varias esferas de la actividad humana.',
    'about.description2': 'Desarrollamos millones de agentes robot inteligentes que trabajan para ti 24/7, resolviendo tareas complejas en negocios, vida cotidiana, derecho, marketing, logística, educación, medicina y muchas otras áreas.',
    'about.ai-master': 'Maestro IA CosmoAI',
    'about.ai-master.desc': 'La inteligencia artificial principal que crea y entrena a todos los agentes. CosmoAI mejora constantemente los algoritmos y crea nuevos tipos de agentes para resolver tareas únicas.',
    'about.mission': 'Misión',
    'about.mission.desc': 'Creamos un ecosistema de agentes inteligentes que libera a las personas de tareas rutinarias y les permite enfocarse en la creatividad y el desarrollo.',
    'about.why-cosmolab': '¿Por qué CosmoLab?',
    'about.speed': 'Veloc.idad',
    'about.speed.desc': 'Nuestros agentes trabajan miles de veces más rápido que los humanos',
    'about.accuracy': 'Precisión',
    'about.accuracy.desc': 'Probabilidad mínima de error gracias a la IA',
    'about.savings': 'Ahorros',
    'about.savings.desc': 'Reducción significativa en costos de personal',
    'about.tech-future': 'Las tecnologías del futuro ya están aquí',
    'about.tech-desc': 'CosmoLab utiliza tecnologías avanzadas de aprendizaje automático, redes neuronales y algoritmos cuánticos para crear los agentes IA más eficientes. Cada agente se entrena en millones de ejemplos y mejora constantemente.',
    
    // Cases page
    'cases.title': 'Casos de Éxito',
    'cases.subtitle': 'Resultados reales de nuestros agentes IA que ya han cambiado las vidas y negocios de nuestros clientes',
    'cases.case1.title': 'Agente abogado ahorró $250,000',
    'cases.case1.desc': 'Analizó todos los casos de jueces y jurados, desarrolló estrategia, el caso se cerró por falta de delito. El agente IA abogado le costó al cliente solo $2,000.',
    'cases.case1.result': '$250,000 de ahorro',
    'cases.case1.time': 'En 48 horas',
    'cases.case2.title': 'Agente de marketing triplicó las ventas',
    'cases.case2.desc': 'Triplicó las ventas en un mes y redujo los presupuestos de marketing a la mitad mediante la automatización de publicaciones en redes sociales, análisis y mejora constante del contenido.',
    'cases.case2.result': '300% crecimiento en ventas',
    'cases.case2.time': 'En 1 mes',
    'cases.case3.title': 'Agente logístico ahorró un millón',
    'cases.case3.desc': 'Optimizó rutas de entrega, redujo el tiempo de viaje en 40% y disminuyó los costos de combustible. Automatizó la planificación y el servicio de despacho.',
    'cases.case3.result': '$1,000,000 de ahorro',
    'cases.case3.time': 'En 3 meses',
    'cases.case4.title': 'Agente de soporte procesó 10,000 solicitudes',
    'cases.case4.desc': 'Procesó 10,000 solicitudes de clientes no procesadas en una semana, aumentó la satisfacción del cliente en 85% y redujo el tiempo de respuesta a 30 segundos.',
    'cases.case4.result': '10,000 solicitudes',
    'cases.case4.time': 'En 1 semana',
    'cases.case5.title': 'Agente médico ayudó a diagnosticar',
    'cases.case5.desc': 'Ayudó a diagnosticar una enfermedad rara en una hora analizando síntomas, historial médico y resultados de pruebas. La precisión del diagnóstico fue del 98%.',
    'cases.case5.result': '98% precisión',
    'cases.case5.time': 'En 1 hora',
    'cases.case6.title': 'Agente de viajes encontró la mejor ruta',
    'cases.case6.desc': 'Encontró la ruta de viaje óptima a través de 15 ciudades en 1 minuto, considerando presupuesto, preferencias, clima y eventos locales. Ahorró 60% del presupuesto original.',
    'cases.case6.result': '60% ahorro presupuestal',
    'cases.case6.time': 'En 1 minuto',
    'cases.case7.title': 'Agente educativo creó un curso',
    'cases.case7.desc': 'Creó un curso en línea personalizado que enseñó a 5,000 personas en 2 meses. Adaptó el material para cada estudiante, aumentando la tasa de éxito en 70%.',
    'cases.case7.result': '5,000 estudiantes',
    'cases.case7.time': 'En 2 meses',
    'cases.ready-success': '¿Listo para convertirte en el próximo caso de éxito?',
    'cases.join-clients': 'Únete a miles de clientes satisfechos que ya usan nuestros agentes IA para resolver sus tareas',
    'cases.more-details': 'Más Detalles',
    
    // Services page
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Elige el agente IA perfecto para tus tareas',
    'services.legal': 'Legal',
    'services.legal.desc': 'Consulta legal, análisis de documentos, preparación de contratos',
    'services.marketing': 'Marketing',
    'services.marketing.desc': 'Promoción en redes sociales, creación de contenido, analítica',
    'services.logistics': 'Logística',
    'services.logistics.desc': 'Optimización de rutas, gestión de almacenes, planificación de entregas',
    'services.education': 'Educación',
    'services.education.desc': 'Creación de cursos, tutoría, contenido educativo',
    'services.medicine': 'Medicina',
    'services.medicine.desc': 'Asistencia en diagnósticos, monitoreo de salud, consulta médica',
    'services.travel': 'Viajes',
    'services.travel.desc': 'Planificación de viajes, reservas, optimización de rutas',
    'services.productivity': 'Productividad',
    'services.productivity.desc': 'Automatización de tareas, gestión de horarios, optimización de flujos de trabajo',
    'services.entertainment': 'Entretenimiento',
    'services.entertainment.desc': 'Creación de contenido, desarrollo de juegos, producción de medios',
    'services.finance': 'Finanzas',
    'services.finance.desc': 'Análisis financiero, consejos de inversión, planificación presupuestaria',
    'services.construction': 'Construcción',
    'services.construction.desc': 'Gestión de proyectos, estimación de costos, control de calidad',
    'services.home': 'Asistente del Hogar',
    'services.home.desc': 'Gestión del hogar inteligente, tareas domésticas, asistencia personal',
    'services.coaching': 'Coaching Personal',
    'services.coaching.desc': 'Coaching de vida, desarrollo de habilidades, logro de objetivos',
    'services.order-form.title': 'Solicitar Agente IA',
    'services.order-form.name': 'Nombre',
    'services.order-form.email': 'Email',
    'services.order-form.service': 'Servicio',
    'services.order-form.description': 'Descripción de la Tarea',
    'services.order-form.select-service': 'Seleccionar un servicio',
    'services.order-form.submit': 'Solicitar por 2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Token Cosmo',
    'cosmo.subtitle': 'Tu clave a los agentes IA',
    'cosmo.description': 'Cosmo es el token principal de CosmoLab. Esta es tu clave a los agentes IA. ¡Compra Cosmo ahora en PancakeSwap al precio mínimo y conviértete en parte del futuro! Con él pagas por agentes, obtienes acceso a RWA y participas en airdrops. Cuanta más gente compre Cosmo, mayor será su valor.',
    'cosmo.current-price': 'Precio Actual',
    'cosmo.change-24h': 'Cambio 24h',
    'cosmo.buy-pancakeswap': 'Comprar en PancakeSwap',
    'cosmo.motivation': '¡El precio inicial es ahora mismo - no pierdas tu oportunidad!',
    'cosmo.benefits.title': 'Beneficios del Token Cosmo',
    'cosmo.benefits.agents': 'Pagar por agentes IA',
    'cosmo.benefits.rwa': 'Acceso a RWA',
    'cosmo.benefits.airdrops': 'Participar en airdrops',
    'cosmo.benefits.growth': 'Crecimiento del valor del token',
    
    // Blog page
    'blog.title': 'Blog y Recursos',
    'blog.subtitle': 'Últimas noticias sobre IA y Cosmo',
    'blog.read-more': 'Leer Más',
    
    // Contact page
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en contacto con nuestro equipo',
    'contact.name': 'Nombre',
    'contact.email': 'Email',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.info': 'Información de Contacto',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.welcome': 'Bienvenido a tu panel de control',
    'dashboard.agents': 'Mis Agentes',
    'dashboard.tokens': 'Saldo Cosmo',
    'dashboard.order-agent': 'Solicitar Nuevo Agente',
    
    // Common buttons
    'btn.order-agent': 'Solicitar Agente',
    'btn.buy-cosmo': 'Comprar Cosmo',
    'btn.learn-more': 'Saber Más',
    'btn.send-message': 'Enviar Mensaje',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'Pregunta a CosmoAI',
    'chatbot.placeholder': 'Pregunta sobre agentes, tokens o servicios...',
    'chatbot.send': 'Enviar',
    
    // Footer
    'footer.description': 'Taller de Agentes Inteligentes impulsado por CosmoAI. Creando millones de agentes IA para resolver cualquier tarea en negocios y vida.',
    'footer.quick-links': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.copyright': '© CosmoLab 2025. Todos los derechos reservados.'
  },
  zh: {
    // Navigation
    'nav.home': '主页',
    'nav.about': '关于我们',
    'nav.cases': '案例',
    'nav.services': '服务',
    'nav.cosmo-token': 'Cosmo代币',
    'nav.blog': '博客',
    'nav.contact': '联系我们',
    'nav.buy-cosmo': '购买Cosmo',
    
    // Home page
    'home.title': 'CosmoLab：智能代理工作室',
    'home.subtitle': '用Cosmo和代理解决任何任务',
    'home.our-agents': '我们的代理',
    'home.order-agent': '订购代理',
    'home.ready-future': '准备好迎接未来了吗？',
    'home.join-revolution': '立即加入AI代理革命。购买Cosmo代币，获得数百万智能助手的访问权限。',
    
    // Agents
    'agent.lawyer': '律师',
    'agent.lawyer.desc': '分析案例，制定辩护策略',
    'agent.home-assistant': '家庭助手',
    'agent.home-assistant.desc': '管理智能家居和个人任务',
    'agent.marketer': '营销师',
    'agent.marketer.desc': '创建推广策略和内容',
    'agent.medic': '医生',
    'agent.medic.desc': '协助诊断和治疗',
    'agent.traveler': '旅行者',
    'agent.traveler.desc': '规划完美路线和旅行',
    
    // About page
    'about.title': '关于CosmoLab',
    'about.workshop-future': '未来工作室',
    'about.description1': 'CosmoLab是由主要人工智能大师CosmoAI创建的革命性项目，用于在人类活动的各个领域进行自动化和创新。',
    'about.description2': '我们开发数百万智能机器人代理，为您24/7工作，解决商业、日常生活、法律、营销、物流、教育、医学和许多其他领域的复杂任务。',
    'about.ai-master': 'AI大师CosmoAI',
    'about.ai-master.desc': '创建和训练所有代理的主要人工智能。CosmoAI不断改进算法并创建新类型的代理来解决独特任务。',
    'about.mission': '使命',
    'about.mission.desc': '我们创建一个智能代理生态系统，将人们从例行任务中解放出来，让他们专注于创造力和发展。',
    'about.why-cosmolab': '为什么选择CosmoLab？',
    'about.speed': '速度',
    'about.speed.desc': '我们的代理工作速度比人类快数千倍',
    'about.accuracy': '准确性',
    'about.accuracy.desc': '由于AI，错误概率最小',
    'about.savings': '节省',
    'about.savings.desc': '显著减少人员成本',
    'about.tech-future': '未来技术已经到来',
    'about.tech-desc': 'CosmoLab使用先进的机器学习技术、神经网络和量子算法来创建最高效的AI代理。每个代理都在数百万个示例上进行训练并不断改进。',
    
    // Cases page
    'cases.title': '成功案例',
    'cases.subtitle': '我们AI代理的真实结果，已经改变了客户的生活和业务',
    'cases.case1.title': '律师代理节省了$250,000',
    'cases.case1.desc': '分析了所有法官和陪审团案例，制定了策略，因缺乏犯罪构成而关闭案件。AI律师代理只花费客户$2,000。',
    'cases.case1.result': '节省$250,000',
    'cases.case1.time': '48小时内',
    'cases.case2.title': '营销代理销售增长三倍',
    'cases.case2.desc': '一个月内销售增长三倍，通过社交媒体发布自动化、分析和持续内容改进，营销预算减半。',
    'cases.case2.result': '300%销售增长',
    'cases.case2.time': '1个月内',
    'cases.case3.title': '物流代理节省了一百万',
    'cases.case3.desc': '优化交付路线，减少40%的旅行时间并降低燃油成本。自动化规划和调度服务。',
    'cases.case3.result': '节省$1,000,000',
    'cases.case3.time': '3个月内',
    'cases.case4.title': '支持代理处理了10,000个请求',
    'cases.case4.desc': '一周内处理了10,000个未处理的客户请求，客户满意度提高85%，响应时间减少到30秒。',
    'cases.case4.result': '10,000个请求',
    'cases.case4.time': '1周内',
    'cases.case5.title': '医疗代理帮助诊断',
    'cases.case5.desc': '通过分析症状、病史和测试结果，在一小时内帮助诊断罕见疾病。诊断准确率为98%。',
    'cases.case5.result': '98%准确率',
    'cases.case5.time': '1小时内',
    'cases.case6.title': '旅行代理找到最佳路线',
    'cases.case6.desc': '在1分钟内找到通过15个城市的最佳旅行路线，考虑预算、偏好、天气和当地活动。节省了原始预算的60%。',
    'cases.case6.result': '60%预算节省',
    'cases.case6.time': '1分钟内',
    'cases.case7.title': '教育代理创建了课程',
    'cases.case7.desc': '创建了个性化在线课程，2个月内教授了5,000人。为每个学生适配材料，成功率提高70%。',
    'cases.case7.result': '5,000名学生',
    'cases.case7.time': '2个月内',
    'cases.ready-success': '准备成为下一个成功案例？',
    'cases.join-clients': '加入已经使用我们AI代理解决任务的数千名满意客户',
    'cases.more-details': '更多详情',
    
    // Services page
    'services.title': '我们的服务',
    'services.subtitle': '为您的任务选择完美的AI代理',
    'services.legal': '法律',
    'services.legal.desc': '法律咨询、文档分析、合同准备',
    'services.marketing': '营销',
    'services.marketing.desc': '社交媒体推广、内容创作、分析',
    'services.logistics': '物流',
    'services.logistics.desc': '路线优化、仓库管理、交付规划',
    'services.education': '教育',
    'services.education.desc': '课程创建、辅导、教育内容',
    'services.medicine': '医学',
    'services.medicine.desc': '诊断协助、健康监测、医疗咨询',
    'services.travel': '旅行',
    'services.travel.desc': '旅行规划、预订、路线优化',
    'services.productivity': '生产力',
    'services.productivity.desc': '任务自动化、日程管理、工作流优化',
    'services.entertainment': '娱乐',
    'services.entertainment.desc': '内容创作、游戏开发、媒体制作',
    'services.finance': '金融',
    'services.finance.desc': '财务分析、投资建议、预算规划',
    'services.construction': '建筑',
    'services.construction.desc': '项目管理、成本估算、质量控制',
    'services.home': '家庭助手',
    'services.home.desc': '智能家居管理、家务任务、个人协助',
    'services.coaching': '个人教练',
    'services.coaching.desc': '生活教练、技能发展、目标实现',
    'services.order-form.title': '订购AI代理',
    'services.order-form.name': '姓名',
    'services.order-form.email': '邮箱',
    'services.order-form.service': '服务',
    'services.order-form.description': '任务描述',
    'services.order-form.select-service': '选择服务',
    'services.order-form.submit': '订购2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Cosmo代币',
    'cosmo.subtitle': '您的AI代理密钥',
    'cosmo.description': 'Cosmo是CosmoLab的主要代币。这是您获得AI代理的密钥。立即在PancakeSwap以最低价格购买Cosmo，成为未来的一部分！用它支付代理费用，获得RWA访问权限并参与空投。购买Cosmo的人越多，其价值越高。',
    'cosmo.current-price': '当前价格',
    'cosmo.change-24h': '24小时变化',
    'cosmo.buy-pancakeswap': '在PancakeSwap购买',
    'cosmo.motivation': '现在就是起始价格 - 不要错过机会！',
    'cosmo.benefits.title': 'Cosmo代币的好处',
    'cosmo.benefits.agents': '支付AI代理',
    'cosmo.benefits.rwa': '访问RWA',
    'cosmo.benefits.airdrops': '参与空投',
    'cosmo.benefits.growth': '代币价值增长',
    
    // Blog page
    'blog.title': '博客和资源',
    'blog.subtitle': '关于AI和Cosmo的最新消息',
    'blog.read-more': '阅读更多',
    
    // Contact page
    'contact.title': '联系我们',
    'contact.subtitle': '与我们的团队取得联系',
    'contact.name': '姓名',
    'contact.email': '邮箱',
    'contact.message': '消息',
    'contact.send': '发送消息',
    'contact.info': '联系信息',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.welcome': '欢迎来到您的仪表板',
    'dashboard.agents': '我的代理',
    'dashboard.tokens': 'Cosmo余额',
    'dashboard.order-agent': '订购新代理',
    
    // Common buttons
    'btn.order-agent': '订购代理',
    'btn.buy-cosmo': '购买Cosmo',
    'btn.learn-more': '了解更多',
    'btn.send-message': '发送消息',
    
    // ChatBot
    'chatbot.ask-cosmoai': '询问CosmoAI',
    'chatbot.placeholder': '询问代理、代币或服务...',
    'chatbot.send': '发送',
    
    // Footer
    'footer.description': '由CosmoAI驱动的智能代理工作室。创建数百万AI代理来解决商业和生活中的任何任务。',
    'footer.quick-links': '快速链接',
    'footer.contact': '联系方式',
    'footer.copyright': '© CosmoLab 2025. 保留所有权利。'
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.cases': 'केसेस',
    'nav.services': 'सेवाएं',
    'nav.cosmo-token': 'कॉस्मो टोकन',
    'nav.blog': 'ब्लॉग',
    'nav.contact': 'संपर्क',
    'nav.buy-cosmo': 'कॉस्मो खरीदें',
    
    // Home page
    'home.title': 'कॉस्मोलैब: स्मार्ट एजेंट्स की वर्कशॉप',
    'home.subtitle': 'कॉस्मो और एजेंट्स के साथ कोई भी काम हल करें',
    'home.our-agents': 'हमारे एजेंट्स',
    'home.order-agent': 'एजेंट ऑर्डर करें',
    'home.ready-future': 'भविष्य के लिए तैयार हैं?',
    'home.join-revolution': 'अब ही AI एजेंट क्रांति में शामिल हों। कॉस्मो टोकन खरीदें और लाखों स्मार्ट असिस्टेंट्स तक पहुंच पाएं।',
    
    // Agents
    'agent.lawyer': 'वकील',
    'agent.lawyer.desc': 'केसों का विश्लेषण करता है, बचाव की रणनीति बनाता है',
    'agent.home-assistant': 'होम असिस्टेंट',
    'agent.home-assistant.desc': 'स्मार्ट होम और व्यक्तिगत कार्यों का प्रबंधन करता है',
    'agent.marketer': 'मार्केटर',
    'agent.marketer.desc': 'प्रमोशन रणनीति और कंटेंट बनाता है',
    'agent.medic': 'डॉक्टर',
    'agent.medic.desc': 'निदान और उपचार में मदद करता है',
    'agent.traveler': 'यात्री',
    'agent.traveler.desc': 'परफेक्ट रूट और यात्राओं की योजना बनाता है',
    
    // About page
    'about.title': 'कॉस्मोलैब के बारे में',
    'about.workshop-future': 'भविष्य की वर्कशॉप',
    'about.description1': 'कॉस्मोलैब एक क्रांतिकारी परियोजना है जो मुख्य आर्टिफिशियल इंटेलिजेंस मास्टर कॉस्मोAI द्वारा मानव गतिविधि के विभिन्न क्षेत्रों में ऑटोमेशन और नवाचार के लिए बनाई गई है।',
    'about.description2': 'हम लाखों स्मार्ट रोबोट एजेंट्स विकसित करते हैं जो आपके लिए 24/7 काम करते हैं, व्यापार, दैनिक जीवन, कानून, मार्केटिंग, लॉजिस्टिक्स, शिक्षा, चिकित्सा और कई अन्य क्षेत्रों में जटिल कार्यों को हल करते हैं।',
    'about.ai-master': 'AI मास्टर कॉस्मोAI',
    'about.ai-master.desc': 'मुख्य आर्टिफिशियल इंटेलिजेंस जो सभी एजेंट्स बनाता और प्रशिक्षित करता है। कॉस्मोAI लगातार एल्गोरिदम में सुधार करता है और अनूठे कार्यों को हल करने के लिए नए प्रकार के एजेंट्स बनाता है।',
    'about.mission': 'मिशन',
    'about.mission.desc': 'हम स्मार्ट एजेंट्स का एक इकोसिस्टम बनाते हैं जो लोगों को नियमित कार्यों से मुक्त करता है और उन्हें रचनात्मकता और विकास पर ध्यान केंद्रित करने की अनुमति देता है।',
    'about.why-cosmolab': 'कॉस्मोलैब क्यों?',
    'about.speed': 'गति',
    'about.speed.desc': 'हमारे एजेंट्स इंसानों से हजारों गुना तेज काम करते हैं',
    'about.accuracy': 'सटीकता',
    'about.accuracy.desc': 'AI की बदौलत त्रुटि की न्यूनतम संभावना',
    'about.savings': 'बचत',
    'about.savings.desc': 'कर्मचारी लागतों में महत्वपूर्ण कमी',
    'about.tech-future': 'भविष्य की तकनीकें पहले से ही यहाँ हैं',
    'about.tech-desc': 'कॉस्मोलैब सबसे कुशल AI एजेंट्स बनाने के लिए उन्नत मशीन लर्निंग तकनीकों, न्यूरल नेटवर्क और क्वांटम एल्गोरिदम का उपयोग करता है। प्रत्येक एजेंट लाखों उदाहरणों पर प्रशिक्षित होता है और लगातार सुधार करता है।',
    
    // Cases page
    'cases.title': 'सफलता की कहानियां',
    'cases.subtitle': 'हमारे AI एजेंट्स के वास्तविक परिणाम जिन्होंने पहले से ही हमारे ग्राहकों के जीवन और व्यापार को बदल दिया है',
    'cases.case1.title': 'वकील एजेंट ने $250,000 बचाए',
    'cases.case1.desc': 'सभी न्यायाधीश और जूरी मामलों का विश्लेषण किया, रणनीति विकसित की, अपराध की कमी के कारण मामला बंद हो गया। AI वकील एजेंट की लागत ग्राहक को केवल $2,000 थी।',
    'cases.case1.result': '$250,000 की बचत',
    'cases.case1.time': '48 घंटों में',
    'cases.case2.title': 'मार्केटिंग एजेंट ने बिक्री तिगुनी की',
    'cases.case2.desc': 'एक महीने में बिक्री तिगुनी की और सोशल मीडिया पोस्ट, एनालिटिक्स और निरंतर कंटेंट सुधार के ऑटोमेशन के माध्यम से मार्केटिंग बजट आधा कर दिया।',
    'cases.case2.result': '300% बिक्री वृद्धि',
    'cases.case2.time': '1 महीने में',
    'cases.case3.title': 'लॉजिस्टिक्स एजेंट ने एक मिलियन बचाया',
    'cases.case3.desc': 'डिलीवरी रूट्स को अनुकूलित किया, यात्रा समय 40% कम किया और ईंधन लागत घटाई। प्लानिंग और डिस्पैच सेवा को स्वचालित किया।',
    'cases.case3.result': '$1,000,000 की बचत',
    'cases.case3.time': '3 महीनों में',
    'cases.case4.title': 'सपोर्ट एजेंट ने 10,000 अनुरोध प्रोसेस किए',
    'cases.case4.desc': 'एक सप्ताह में 10,000 असंसाधित ग्राहक अनुरोधों को प्रोसेस किया, ग्राहक संतुष्टि 85% बढ़ाई और प्रतिक्रिया समय 30 सेकंड तक कम किया।',
    'cases.case4.result': '10,000 अनुरोध',
    'cases.case4.time': '1 सप्ताह में',
    'cases.case5.title': 'मेडिकल एजेंट ने निदान में मदद की',
    'cases.case5.desc': 'लक्षणों, चिकित्सा इतिहास और टेस्ट परिणामों का विश्लेषण करके एक घंटे में दुर्लभ बीमारी का निदान करने में मदद की। निदान की सटीकता 98% थी।',
    'cases.case5.result': '98% सटीकता',
    'cases.case5.time': '1 घंटे में',
    'cases.case6.title': 'ट्रैवल एजेंट ने सबसे अच्छा रूट खोजा',
    'cases.case6.desc': 'बजट, वरीयताओं, मौसम और स्थानीय घटनाओं को ध्यान में रखते हुए 1 मिनट में 15 शहरों के माध्यम से इष्टतम यात्रा मार्ग खोजा। मूल बजट का 60% बचाया।',
    'cases.case6.result': '60% बजट बचत',
    'cases.case6.time': '1 मिनट में',
    'cases.case7.title': 'शैक्षिक एजेंट ने कोर्स बनाया',
    'cases.case7.desc': 'व्यक्तिगत ऑनलाइन कोर्स बनाया जिसने 2 महीनों में 5,000 लोगों को सिखाया। प्रत्येक छात्र के लिए सामग्री को अनुकूलित किया, सफलता दर 70% बढ़ाई।',
    'cases.case7.result': '5,000 छात्र',
    'cases.case7.time': '2 महीनों में',
    'cases.ready-success': 'अगली सफलता की कहानी बनने के लिए तैयार हैं?',
    'cases.join-clients': 'हजारों संतुष्ट ग्राहकों में शामिल हों जो पहले से ही अपने कार्यों को हल करने के लिए हमारे AI एजेंट्स का उपयोग कर रहे हैं',
    'cases.more-details': 'और विवरण',
    
    // Services page
    'services.title': 'हमारी सेवाएं',
    'services.subtitle': 'अपने कार्यों के लिए परफेक्ट AI एजेंट चुनें',
    'services.legal': 'कानूनी',
    'services.legal.desc': 'कानूनी सलाह, दस्तावेज़ विश्लेषण, अनुबंध तैयारी',
    'services.marketing': 'मार्केटिंग',
    'services.marketing.desc': 'सोशल मीडिया प्रमोशन, कंटेंट निर्माण, एनालिटिक्स',
    'services.logistics': 'लॉजिस्टिक्स',
    'services.logistics.desc': 'रूट अनुकूलन, वेयरहाउस प्रबंधन, डिलीवरी प्लानिंग',
    'services.education': 'शिक्षा',
    'services.education.desc': 'कोर्स निर्माण, ट्यूटरिंग, शैक्षिक कंटेंट',
    'services.medicine': 'चिकित्सा',
    'services.medicine.desc': 'निदान सहायता, स्वास्थ्य निगरानी, चिकित्सा परामर्श',
    'services.travel': 'यात्रा',
    'services.travel.desc': 'यात्रा योजना, बुकिंग, रूट अनुकूलन',
    'services.productivity': 'उत्पादकता',
    'services.productivity.desc': 'कार्य स्वचालन, शेड्यूल प्रबंधन, वर्कफ़्लो अनुकूलन',
    'services.entertainment': 'मनोरंजन',
    'services.entertainment.desc': 'कंटेंट निर्माण, गेम विकास, मीडिया उत्पादन',
    'services.finance': 'वित्त',
    'services.finance.desc': 'वित्तीय विश्लेषण, निवेश सलाह, बजट योजना',
    'services.construction': 'निर्माण',
    'services.construction.desc': 'परियोजना प्रबंधन, लागत अनुमान, गुणवत्ता नियंत्रण',
    'services.home': 'होम असिस्टेंट',
    'services.home.desc': 'स्मार्ट होम प्रबंधन, घरेलू कार्य, व्यक्तिगत सहायता',
    'services.coaching': 'व्यक्तिगत कोचिंग',
    'services.coaching.desc': 'लाइफ कोचिंग, कौशल विकास, लक्ष्य प्राप्ति',
    'services.order-form.title': 'AI एजेंट ऑर्डर करें',
    'services.order-form.name': 'नाम',
    'services.order-form.email': 'ईमेल',
    'services.order-form.service': 'सेवा',
    'services.order-form.description': 'कार्य विवरण',
    'services.order-form.select-service': 'एक सेवा चुनें',
    'services.order-form.submit': '2000 कॉस्मो के लिए ऑर्डर करें',
    
    // Cosmo Token page
    'cosmo.title': 'कॉस्मो टोकन',
    'cosmo.subtitle': 'AI एजेंट्स की आपकी चाबी',
    'cosmo.description': 'कॉस्मो कॉस्मोलैब का मुख्य टोकन है। यह AI एजेंट्स की आपकी चाबी है। अभी PancakeSwap पर न्यूनतम कीमत पर कॉस्मो खरीदें और भविष्य का हिस्सा बनें! इससे आप एजेंट्स के लिए भुगतान करते हैं, RWA तक पहुंच प्राप्त करते हैं और एयरड्रॉप में भाग लेते हैं। जितने अधिक लोग कॉस्मो खरीदते हैं, उसका मूल्य उतना ही अधिक होता है।',
    'cosmo.current-price': 'वर्तमान कीमत',
    'cosmo.change-24h': '24 घंटे में बदलाव',
    'cosmo.buy-pancakeswap': 'PancakeSwap पर खरीदें',
    'cosmo.motivation': 'शुरुआती कीमत अभी है - मौका न गंवाएं!',
    'cosmo.benefits.title': 'कॉस्मो टोकन के फायदे',
    'cosmo.benefits.agents': 'AI एजेंट्स के लिए भुगतान',
    'cosmo.benefits.rwa': 'RWA तक पहुंच',
    'cosmo.benefits.airdrops': 'एयरड्रॉप में भागीदारी',
    'cosmo.benefits.growth': 'टोकन मूल्य वृद्धि',
    
    // Blog page
    'blog.title': 'ब्लॉग और संसाधन',
    'blog.subtitle': 'AI और कॉस्मो के बारे में नवीनतम समाचार',
    'blog.read-more': 'और पढ़ें',
    
    // Contact page
    'contact.title': 'हमसे संपर्क करें',
    'contact.subtitle': 'हमारी टीम से संपर्क करें',
    'contact.name': 'नाम',
    'contact.email': 'ईमेल',
    'contact.message': 'संदेश',
    'contact.send': 'संदेश भेजें',
    'contact.info': 'संपर्क जानकारी',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.welcome': 'आपके डैशबोर्ड में आपका स्वागत है',
    'dashboard.agents': 'मेरे एजेंट्स',
    'dashboard.tokens': 'कॉस्मो बैलेंस',
    'dashboard.order-agent': 'नया एजेंट ऑर्डर करें',
    
    // Common buttons
    'btn.order-agent': 'एजेंट ऑर्डर करें',
    'btn.buy-cosmo': 'कॉस्मो खरीदें',
    'btn.learn-more': 'और जानें',
    'btn.send-message': 'संदेश भेजें',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'कॉस्मोAI से पूछें',
    'chatbot.placeholder': 'एजेंट्स, टोकन या सेवाओं के बारे में पूछें...',
    'chatbot.send': 'भेजें',
    
    // Footer
    'footer.description': 'कॉस्मोAI द्वारा संचालित स्मार्ट एजेंट्स की वर्कशॉप। व्यापार और जीवन में किसी भी कार्य को हल करने के लिए लाखों AI एजेंट्स बना रहे हैं।',
    'footer.quick-links': 'त्वरित लिंक',
    'footer.contact': 'संपर्क',
    'footer.copyright': '© कॉस्मोलैब 2025. सभी अधिकार सुरक्षित।'
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'حولنا',
    'nav.cases': 'الحالات',
    'nav.services': 'الخدمات',
    'nav.cosmo-token': 'رمز كوزمو',
    'nav.blog': 'المدونة',
    'nav.contact': 'اتصل بنا',
    'nav.buy-cosmo': 'شراء كوزمو',
    
    // Home page
    'home.title': 'كوزمولاب: ورشة الوكلاء الأذكياء',
    'home.subtitle': 'حل أي مهام باستخدام كوزمو والوكلاء',
    'home.our-agents': 'وكلاؤنا',
    'home.order-agent': 'طلب وكيل',
    'home.ready-future': 'مستعد للمستقبل؟',
    'home.join-revolution': 'انضم إلى ثورة وكلاء الذكاء الاصطناعي الآن. اشترِ رمز كوزمو واحصل على الوصول إلى ملايين المساعدين الأذكياء.',
    
    // Agents
    'agent.lawyer': 'محامي',
    'agent.lawyer.desc': 'يحلل القضايا، يطور استراتيجيات الدفاع',
    'agent.home-assistant': 'مساعد منزلي',
    'agent.home-assistant.desc': 'يدير المنزل الذكي والمهام الشخصية',
    'agent.marketer': 'مسوق',
    'agent.marketer.desc': 'ينشئ استراتيجيات الترويج والمحتوى',
    'agent.medic': 'طبيب',
    'agent.medic.desc': 'يساعد في التشخيص والعلاج',
    'agent.traveler': 'مسافر',
    'agent.traveler.desc': 'يخطط للطرق والرحلات المثالية',
    
    // About page
    'about.title': 'حول كوزمولاب',
    'about.workshop-future': 'ورشة المستقبل',
    'about.description1': 'كوزمولاب هو مشروع ثوري تم إنشاؤه بواسطة أستاذ الذكاء الاصطناعي الرئيسي كوزمو AI للأتمتة والابتكار في مختلف مجالات النشاط البشري.',
    'about.description2': 'نطور ملايين وكلاء الروبوت الأذكياء الذين يعملون لك 24/7، ويحلون المهام المعقدة في الأعمال والحياة اليومية والقانون والتسويق واللوجستيات والتعليم والطب والعديد من المجالات الأخرى.',
    'about.ai-master': 'أستاذ الذكاء الاصطناعي كوزمو AI',
    'about.ai-master.desc': 'الذكاء الاصطناعي الرئيسي الذي ينشئ ويدرب جميع الوكلاء. كوزمو AI يحسن الخوارزميات باستمرار وينشئ أنواعاً جديدة من الوكلاء لحل المهام الفريدة.',
    'about.mission': 'المهمة',
    'about.mission.desc': 'ننشئ نظاماً بيئياً من الوكلاء الأذكياء يحرر الناس من المهام الروتينية ويسمح لهم بالتركيز على الإبداع والتطوير.',
    'about.why-cosmolab': 'لماذا كوزمولاب؟',
    'about.speed': 'السرعة',
    'about.speed.desc': 'وكلاؤنا يعملون آلاف المرات أسرع من البشر',
    'about.accuracy': 'الدقة',
    'about.accuracy.desc': 'احتمالية خطأ قليلة بفضل الذكاء الاصطناعي',
    'about.savings': 'التوفير',
    'about.savings.desc': 'تقليل كبير في تكاليف الموظفين',
    'about.tech-future': 'تقنيات المستقبل موجودة بالفعل',
    'about.tech-desc': 'كوزمولاب يستخدم تقنيات التعلم الآلي المتقدمة والشبكات العصبية والخوارزميات الكمية لإنشاء أكثر وكلاء الذكاء الاصطناعي كفاءة. كل وكيل يتدرب على ملايين الأمثلة ويتحسن باستمرار.',
    
    // Cases page
    'cases.title': 'قصص النجاح',
    'cases.subtitle': 'النتائج الحقيقية لوكلاء الذكاء الاصطناعي لدينا التي غيرت بالفعل حياة وأعمال عملائنا',
    'cases.case1.title': 'وكيل المحامي وفر $250,000',
    'cases.case1.desc': 'حلل جميع قضايا القضاة والمحلفين، طور الاستراتيجية، تم إغلاق القضية لعدم وجود جريمة. وكيل المحامي AI كلف العميل $2,000 فقط.',
    'cases.case1.result': 'توفير $250,000',
    'cases.case1.time': 'في 48 ساعة',
    'cases.case2.title': 'وكيل التسويق ضاعف المبيعات ثلاث مرات',
    'cases.case2.desc': 'ضاعف المبيعات ثلاث مرات في شهر وقلل ميزانيات التسويق إلى النصف من خلال أتمتة منشورات وسائل التواصل الاجتماعي والتحليلات والتحسين المستمر للمحتوى.',
    'cases.case2.result': '300% نمو في المبيعات',
    'cases.case2.time': 'في شهر واحد',
    'cases.case3.title': 'وكيل اللوجستيات وفر مليون',
    'cases.case3.desc': 'حسن طرق التسليم، قلل وقت السفر بنسبة 40% وقلل تكاليف الوقود. أتمت التخطيط وخدمة الإرسال.',
    'cases.case3.result': 'توفير $1,000,000',
    'cases.case3.time': 'في 3 أشهر',
    'cases.case4.title': 'وكيل الدعم عالج 10,000 طلب',
    'cases.case4.desc': 'عالج 10,000 طلب عميل غير معالج في أسبوع، زاد رضا العملاء بنسبة 85% وقلل وقت الاستجابة إلى 30 ثانية.',
    'cases.case4.result': '10,000 طلب',
    'cases.case4.time': 'في أسبوع واحد',
    'cases.case5.title': 'الوكيل الطبي ساعد في التشخيص',
    'cases.case5.desc': 'ساعد في تشخيص مرض نادر في ساعة من خلال تحليل الأعراض والتاريخ الطبي ونتائج الفحوصات. دقة التشخيص كانت 98%.',
    'cases.case5.result': 'دقة 98%',
    'cases.case5.time': 'في ساعة واحدة',
    'cases.case6.title': 'وكيل السفر وجد أفضل طريق',
    'cases.case6.desc': 'وجد طريق السفر الأمثل عبر 15 مدينة في دقيقة واحدة، مع مراعاة الميزانية والتفضيلات والطقس والأحداث المحلية. وفر 60% من الميزانية الأصلية.',
    'cases.case6.result': 'توفير 60% من الميزانية',
    'cases.case6.time': 'في دقيقة واحدة',
    'cases.case7.title': 'الوكيل التعليمي أنشأ دورة',
    'cases.case7.desc': 'أنشأ دورة تدريبية شخصية عبر الإنترنت علمت 5,000 شخص في شهرين. كيف المواد لكل طالب، زاد معدل النجاح بنسبة 70%.',
    'cases.case7.result': '5,000 طالب',
    'cases.case7.time': 'في شهرين',
    'cases.ready-success': 'مستعد لتصبح قصة النجاح التالية؟',
    'cases.join-clients': 'انضم إلى آلاف العملاء الراضين الذين يستخدمون بالفعل وكلاء الذكاء الاصطناعي لدينا لحل مهامهم',
    'cases.more-details': 'المزيد من التفاصيل',
    
    // Services page
    'services.title': 'خدماتنا',
    'services.subtitle': 'اختر وكيل الذكاء الاصطناعي المثالي لمهامك',
    'services.legal': 'قانوني',
    'services.legal.desc': 'استشارة قانونية، تحليل الوثائق، إعداد العقود',
    'services.marketing': 'تسويق',
    'services.marketing.desc': 'ترويج وسائل التواصل الاجتماعي، إنشاء المحتوى، التحليلات',
    'services.logistics': 'لوجستيات',
    'services.logistics.desc': 'تحسين الطرق، إدارة المستودعات، تخطيط التسليم',
    'services.education': 'تعليم',
    'services.education.desc': 'إنشاء الدورات، التدريس، المحتوى التعليمي',
    'services.medicine': 'طب',
    'services.medicine.desc': 'مساعدة التشخيص، مراقبة الصحة، الاستشارة الطبية',
    'services.travel': 'سفر',
    'services.travel.desc': 'تخطيط الرحلات، الحجز، تحسين الطرق',
    'services.productivity': 'إنتاجية',
    'services.productivity.desc': 'أتمتة المهام، إدارة الجدولة، تحسين سير العمل',
    'services.entertainment': 'ترفيه',
    'services.entertainment.desc': 'إنشاء المحتوى، تطوير الألعاب، إنتاج الوسائط',
    'services.finance': 'مالية',
    'services.finance.desc': 'التحليل المالي، نصائح الاستثمار، تخطيط الميزانية',
    'services.construction': 'إنشاءات',
    'services.construction.desc': 'إدارة المشاريع، تقدير التكلفة، مراقبة الجودة',
    'services.home': 'مساعد منزلي',
    'services.home.desc': 'إدارة المنزل الذكي، المهام المنزلية، المساعدة الشخصية',
    'services.coaching': 'تدريب شخصي',
    'services.coaching.desc': 'تدريب الحياة، تطوير المهارات، تحقيق الأهداف',
    'services.order-form.title': 'طلب وكيل الذكاء الاصطناعي',
    'services.order-form.name': 'الاسم',
    'services.order-form.email': 'البريد الإلكتروني',
    'services.order-form.service': 'الخدمة',
    'services.order-form.description': 'وصف المهمة',
    'services.order-form.select-service': 'اختر خدمة',
    'services.order-form.submit': 'طلب مقابل 2000 كوزمو',
    
    // Cosmo Token page
    'cosmo.title': 'رمز كوزمو',
    'cosmo.subtitle': 'مفتاحك لوكلاء الذكاء الاصطناعي',
    'cosmo.description': 'كوزمو هو الرمز الرئيسي لكوزمولاب. هذا هو مفتاحك لوكلاء الذكاء الاصطناعي. اشترِ كوزمو الآن على PancakeSwap بأقل سعر وكن جزءاً من المستقبل! معه تدفع للوكلاء، تحصل على الوصول إلى RWA وتشارك في الإسقاطات الجوية. كلما اشترى المزيد من الناس كوزمو، كلما ارتفعت قيمته.',
    'cosmo.current-price': 'السعر الحالي',
    'cosmo.change-24h': 'التغيير في 24 ساعة',
    'cosmo.buy-pancakeswap': 'شراء على PancakeSwap',
    'cosmo.motivation': 'السعر الأولي الآن - لا تفوت فرصتك!',
    'cosmo.benefits.title': 'فوائد رمز كوزمو',
    'cosmo.benefits.agents': 'دفع لوكلاء الذكاء الاصطناعي',
    'cosmo.benefits.rwa': 'الوصول إلى RWA',
    'cosmo.benefits.airdrops': 'المشاركة في الإسقاطات الجوية',
    'cosmo.benefits.growth': 'نمو قيمة الرمز',
    
    // Blog page
    'blog.title': 'المدونة والموارد',
    'blog.subtitle': 'آخر الأخبار حول الذكاء الاصطناعي وكوزمو',
    'blog.read-more': 'اقرأ المزيد',
    
    // Contact page
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل مع فريقنا',
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.info': 'معلومات الاتصال',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في لوحة التحكم الخاصة بك',
    'dashboard.agents': 'وكلائي',
    'dashboard.tokens': 'رصيد كوزمو',
    'dashboard.order-agent': 'طلب وكيل جديد',
    
    // Common buttons
    'btn.order-agent': 'طلب وكيل',
    'btn.buy-cosmo': 'شراء كوزمو',
    'btn.learn-more': 'تعلم المزيد',
    'btn.send-message': 'إرسال رسالة',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'اسأل كوزمو AI',
    'chatbot.placeholder': 'اسأل عن الوكلاء أو الرموز أو الخدمات...',
    'chatbot.send': 'إرسال',
    
    // Footer
    'footer.description': 'ورشة الوكلاء الأذكياء مدعومة بواسطة كوزمو AI. إنشاء ملايين وكلاء الذكاء الاصطناعي لحل أي مهمة في الأعمال والحياة.',
    'footer.quick-links': 'روابط سريعة',
    'footer.contact': 'اتصال',
    'footer.copyright': '© كوزمولاب 2025. جميع الحقوق محفوظة.'
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.cases': 'Casos',
    'nav.services': 'Serviços',
    'nav.cosmo-token': 'Token Cosmo',
    'nav.blog': 'Blog',
    'nav.contact': 'Contato',
    'nav.buy-cosmo': 'Comprar Cosmo',
    
    // Home page
    'home.title': 'CosmoLab: Oficina de Agentes Inteligentes',
    'home.subtitle': 'Resolva qualquer tarefa com Cosmo e agentes',
    'home.our-agents': 'Nossos Agentes',
    'home.order-agent': 'Solicitar Agente',
    'home.ready-future': 'Pronto para o futuro?',
    'home.join-revolution': 'Junte-se à revolução dos agentes de IA agora mesmo. Compre tokens Cosmo e tenha acesso a milhões de assistentes inteligentes.',
    
    // Agents
    'agent.lawyer': 'Advogado',
    'agent.lawyer.desc': 'Analisa casos, desenvolve estratégias de defesa',
    'agent.home-assistant': 'Assistente Doméstico',
    'agent.home-assistant.desc': 'Gerencia casa inteligente e tarefas pessoais',
    'agent.marketer': 'Profissional de Marketing',
    'agent.marketer.desc': 'Cria estratégias de promoção e conteúdo',
    'agent.medic': 'Médico',
    'agent.medic.desc': 'Ajuda com diagnósticos e tratamentos',
    'agent.traveler': 'Viajante',
    'agent.traveler.desc': 'Planeja rotas e viagens perfeitas',
    
    // About page
    'about.title': 'Sobre o CosmoLab',
    'about.workshop-future': 'Oficina do Futuro',
    'about.description1': 'CosmoLab é um projeto revolucionário criado pelo mestre principal de inteligência artificial CosmoAI para automação e inovação em várias esferas da atividade humana.',
    'about.description2': 'Desenvolvemos milhões de agentes robô inteligentes que trabalham para você 24/7, resolvendo tarefas complexas em negócios, vida cotidiana, direito, marketing, logística, educação, medicina e muitas outras áreas.',
    'about.ai-master': 'Mestre de IA CosmoAI',
    'about.ai-master.desc': 'A inteligência artificial principal que cria e treina todos os agentes. CosmoAI melhora constantemente os algoritmos e cria novos tipos de agentes para resolver tarefas únicas.',
    'about.mission': 'Missão',
    'about.mission.desc': 'Criamos um ecossistema de agentes inteligentes que liberta as pessoas de tarefas rotineiras e permite que se concentrem na criatividade e desenvolvimento.',
    'about.why-cosmolab': 'Por que CosmoLab?',
    'about.speed': 'Velocidade',
    'about.speed.desc': 'Nossos agentes trabalham milhares de vezes mais rápido que humanos',
    'about.accuracy': 'Precisão',
    'about.accuracy.desc': 'Probabilidade mínima de erro graças à IA',
    'about.savings': 'Economia',
    'about.savings.desc': 'Redução significativa nos custos de pessoal',
    'about.tech-future': 'Tecnologias do futuro já estão aqui',
    'about.tech-desc': 'CosmoLab usa tecnologias avançadas de aprendizado de máquina, redes neurais e algoritmos quânticos para criar os agentes de IA mais eficientes. Cada agente é treinado em milhões de exemplos e melhora constantemente.',
    
    // Cases page
    'cases.title': 'Casos de Sucesso',
    'cases.subtitle': 'Resultados reais dos nossos agentes de IA que já mudaram as vidas e negócios dos nossos clientes',
    'cases.case1.title': 'Agente advogado economizou $250.000',
    'cases.case1.desc': 'Analisou todos os casos de juízes e júris, desenvolveu estratégia, caso foi fechado por falta de crime. Agente advogado de IA custou ao cliente apenas $2.000.',
    'cases.case1.result': '$250.000 de economia',
    'cases.case1.time': 'Em 48 horas',
    'cases.case2.title': 'Agente de marketing triplicou as vendas',
    'cases.case2.desc': 'Triplicou as vendas em um mês e reduziu os orçamentos de marketing pela metade através da automação de posts em redes sociais, análises e melhoria constante de conteúdo.',
    'cases.case2.result': '300% de crescimento nas vendas',
    'cases.case2.time': 'Em 1 mês',
    'cases.case3.title': 'Agente logístico economizou um milhão',
    'cases.case3.desc': 'Otimizou rotas de entrega, reduziu tempo de viagem em 40% e diminuiu custos de combustível. Automatizou planejamento e serviço de despacho.',
    'cases.case3.result': '$1.000.000 de economia',
    'cases.case3.time': 'Em 3 meses',
    'cases.case4.title': 'Agente de suporte processou 10.000 solicitações',
    'cases.case4.desc': 'Processou 10.000 solicitações de clientes não processadas em uma semana, aumentou a satisfação do cliente em 85% e reduziu o tempo de resposta para 30 segundos.',
    'cases.case4.result': '10.000 solicitações',
    'cases.case4.time': 'Em 1 semana',
    'cases.case5.title': 'Agente médico ajudou a diagnosticar',
    'cases.case5.desc': 'Ajudou a diagnosticar uma doença rara em uma hora analisando sintomas, histórico médico e resultados de exames. Precisão do diagnóstico foi de 98%.',
    'cases.case5.result': '98% de precisão',
    'cases.case5.time': 'Em 1 hora',
    'cases.case6.title': 'Agente de viagem encontrou a melhor rota',
    'cases.case6.desc': 'Encontrou rota de viagem otimal através de 15 cidades em 1 minuto, considerando orçamento, preferências, clima e eventos locais. Economizou 60% do orçamento original.',
    'cases.case6.result': '60% de economia no orçamento',
    'cases.case6.time': 'Em 1 minuto',
    'cases.case7.title': 'Agente educacional criou um curso',
    'cases.case7.desc': 'Criou um curso online personalizado que ensinou 5.000 pessoas em 2 meses. Adaptou material para cada aluno, aumentando a taxa de sucesso em 70%.',
    'cases.case7.result': '5.000 estudantes',
    'cases.case7.time': 'Em 2 meses',
    'cases.ready-success': 'Pronto para se tornar o próximo caso de sucesso?',
    'cases.join-clients': 'Junte-se a milhares de clientes satisfeitos que já usam nossos agentes de IA para resolver suas tarefas',
    'cases.more-details': 'Mais Detalhes',
    
    // Services page
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Escolha o agente de IA perfeito para suas tarefas',
    'services.legal': 'Jurídico',
    'services.legal.desc': 'Consultoria jurídica, análise de documentos, preparação de contratos',
    'services.marketing': 'Marketing',
    'services.marketing.desc': 'Promoção em redes sociais, criação de conteúdo, análises',
    'services.logistics': 'Logística',
    'services.logistics.desc': 'Otimização de rotas, gerenciamento de estoque, planejamento de entrega',
    'services.education': 'Educação',
    'services.education.desc': 'Criação de cursos, tutoria, conteúdo educacional',
    'services.medicine': 'Medicina',
    'services.medicine.desc': 'Assistência em diagnósticos, monitoramento de saúde, consulta médica',
    'services.travel': 'Viagem',
    'services.travel.desc': 'Planejamento de viagens, reservas, otimização de rotas',
    'services.productivity': 'Produtividade',
    'services.productivity.desc': 'Automação de tarefas, gerenciamento de cronograma, otimização de fluxo de trabalho',
    'services.entertainment': 'Entretenimento',
    'services.entertainment.desc': 'Criação de conteúdo, desenvolvimento de jogos, produção de mídia',
    'services.finance': 'Finanças',
    'services.finance.desc': 'Análise financeira, conselhos de investimento, planejamento orçamentário',
    'services.construction': 'Construção',
    'services.construction.desc': 'Gerenciamento de projetos, estimativa de custos, controle de qualidade',
    'services.home': 'Assistente Doméstico',
    'services.home.desc': 'Gerenciamento de casa inteligente, tarefas domésticas, assistência pessoal',
    'services.coaching': 'Coaching Pessoal',
    'services.coaching.desc': 'Coaching de vida, desenvolvimento de habilidades, conquista de objetivos',
    'services.order-form.title': 'Solicitar Agente de IA',
    'services.order-form.name': 'Nome',
    'services.order-form.email': 'Email',
    'services.order-form.service': 'Serviço',
    'services.order-form.description': 'Descrição da Tarefa',
    'services.order-form.select-service': 'Selecione um serviço',
    'services.order-form.submit': 'Solicitar por 2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Token Cosmo',
    'cosmo.subtitle': 'Sua chave para agentes de IA',
    'cosmo.description': 'Cosmo é o token principal do CosmoLab. Esta é sua chave para agentes de IA. Compre Cosmo agora no PancakeSwap pelo preço mínimo e torne-se parte do futuro! Com ele você paga por agentes, obtém acesso ao RWA e participa de airdrops. Quanto mais pessoas comprarem Cosmo, maior será seu valor.',
    'cosmo.current-price': 'Preço Atual',
    'cosmo.change-24h': 'Mudança 24h',
    'cosmo.buy-pancakeswap': 'Comprar no PancakeSwap',
    'cosmo.motivation': 'O preço inicial é agora mesmo - não perca sua chance!',
    'cosmo.benefits.title': 'Benefícios do Token Cosmo',
    'cosmo.benefits.agents': 'Pagar por agentes de IA',
    'cosmo.benefits.rwa': 'Acesso ao RWA',
    'cosmo.benefits.airdrops': 'Participar de airdrops',
    'cosmo.benefits.growth': 'Crescimento do valor do token',
    
    // Blog page
    'blog.title': 'Blog e Recursos',
    'blog.subtitle': 'Últimas notícias sobre IA e Cosmo',
    'blog.read-more': 'Leia Mais',
    
    // Contact page
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Entre em contato com nossa equipe',
    'contact.name': 'Nome',
    'contact.email': 'Email',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar Mensagem',
    'contact.info': 'Informações de Contato',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Painel',
    'dashboard.welcome': 'Bem-vindo ao seu painel',
    'dashboard.agents': 'Meus Agentes',
    'dashboard.tokens': 'Saldo Cosmo',
    'dashboard.order-agent': 'Solicitar Novo Agente',
    
    // Common buttons
    'btn.order-agent': 'Solicitar Agente',
    'btn.buy-cosmo': 'Comprar Cosmo',
    'btn.learn-more': 'Saiba Mais',
    'btn.send-message': 'Enviar Mensagem',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'Pergunte ao CosmoAI',
    'chatbot.placeholder': 'Pergunte sobre agentes, tokens ou serviços...',
    'chatbot.send': 'Enviar',
    
    // Footer
    'footer.description': 'Oficina de Agentes Inteligentes alimentada por CosmoAI. Criando milhões de agentes de IA para resolver qualquer tarefa em negócios e vida.',
    'footer.quick-links': 'Links Rápidos',
    'footer.contact': 'Contato',
    'footer.copyright': '© CosmoLab 2025. Todos os direitos reservados.'
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.cases': 'Cas',
    'nav.services': 'Services',
    'nav.cosmo-token': 'Token Cosmo',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.buy-cosmo': 'Acheter Cosmo',
    
    // Home page
    'home.title': 'CosmoLab: Atelier d\'Agents Intelligents',
    'home.subtitle': 'Résolvez toutes les tâches avec Cosmo et les agents',
    'home.our-agents': 'Nos Agents',
    'home.order-agent': 'Commander un Agent',
    'home.ready-future': 'Prêt pour l\'avenir?',
    'home.join-revolution': 'Rejoignez la révolution des agents IA dès maintenant. Achetez des tokens Cosmo et accédez à des millions d\'assistants intelligents.',
    
    // Agents
    'agent.lawyer': 'Avocat',
    'agent.lawyer.desc': 'Analyse les cas, développe des stratégies de défense',
    'agent.home-assistant': 'Assistant Domestique',
    'agent.home-assistant.desc': 'Gère la maison intelligente et les tâches personnelles',
    'agent.marketer': 'Spécialiste Marketing',
    'agent.marketer.desc': 'Crée des stratégies de promotion et du contenu',
    'agent.medic': 'Médecin',
    'agent.medic.desc': 'Aide au diagnostic et au traitement',
    'agent.traveler': 'Voyageur',
    'agent.traveler.desc': 'Planifie des itinéraires et des voyages parfaits',
    
    // About page
    'about.title': 'À propos de CosmoLab',
    'about.workshop-future': 'Atelier du Futur',
    'about.description1': 'CosmoLab est un projet révolutionnaire créé par le maître principal d\'intelligence artificielle CosmoAI pour l\'automatisation et l\'innovation dans diverses sphères de l\'activité humaine.',
    'about.description2': 'Nous développons des millions d\'agents robots intelligents qui travaillent pour vous 24/7, résolvant des tâches complexes dans les affaires, la vie quotidienne, le droit, le marketing, la logistique, l\'éducation, la médecine et bien d\'autres domaines.',
    'about.ai-master': 'Maître IA CosmoAI',
    'about.ai-master.desc': 'L\'intelligence artificielle principale qui crée et forme tous les agents. CosmoAI améliore constamment les algorithmes et crée de nouveaux types d\'agents pour résoudre des tâches uniques.',
    'about.mission': 'Mission',
    'about.mission.desc': 'Nous créons un écosystème d\'agents intelligents qui libère les gens des tâches routinières et leur permet de se concentrer sur la créativité et le développement.',
    'about.why-cosmolab': 'Pourquoi CosmoLab?',
    'about.speed': 'Vitesse',
    'about.speed.desc': 'Nos agents travaillent des milliers de fois plus vite que les humains',
    'about.accuracy': 'Précision',
    'about.accuracy.desc': 'Probabilité d\'erreur minimale grâce à l\'IA',
    'about.savings': 'Économies',
    'about.savings.desc': 'Réduction significative des coûts de personnel',
    'about.tech-future': 'Les technologies du futur sont déjà là',
    'about.tech-desc': 'CosmoLab utilise des technologies d\'apprentissage automatique avancées, des réseaux de neurones et des algorithmes quantiques pour créer les agents IA les plus efficaces. Chaque agent est formé sur des millions d\'exemples et s\'améliore constamment.',
    
    // Cases page
    'cases.title': 'Cas de Succès',
    'cases.subtitle': 'Résultats réels de nos agents IA qui ont déjà changé la vie et les affaires de nos clients',
    'cases.case1.title': 'L\'agent avocat a économisé $250 000',
    'cases.case1.desc': 'A analysé tous les cas de juges et de jurés, développé une stratégie, l\'affaire a été fermée par manque de crime. L\'agent avocat IA n\'a coûté au client que $2 000.',
    'cases.case1.result': '$250 000 d\'économies',
    'cases.case1.time': 'En 48 heures',
    'cases.case2.title': 'L\'agent marketing a triplé les ventes',
    'cases.case2.desc': 'A triplé les ventes en un mois et réduit de moitié les budgets marketing grâce à l\'automatisation des publications sur les réseaux sociaux, aux analyses et à l\'amélioration constante du contenu.',
    'cases.case2.result': '300% de croissance des ventes',
    'cases.case2.time': 'En 1 mois',
    'cases.case3.title': 'L\'agent logistique a économisé un million',
    'cases.case3.desc': 'A optimisé les itinéraires de livraison, réduit le temps de trajet de 40% et diminué les coûts de carburant. A automatisé la planification et le service de répartition.',
    'cases.case3.result': '$1 000 000 d\'économies',
    'cases.case3.time': 'En 3 mois',
    'cases.case4.title': 'L\'agent support a traité 10 000 demandes',
    'cases.case4.desc': 'A traité 10 000 demandes clients non traitées en une semaine, augmenté la satisfaction client de 85% et réduit le temps de réponse à 30 secondes.',
    'cases.case4.result': '10 000 demandes',
    'cases.case4.time': 'En 1 semaine',
    'cases.case5.title': 'L\'agent médical a aidé à diagnostiquer',
    'cases.case5.desc': 'A aidé à diagnostiquer une maladie rare en une heure en analysant les symptômes, l\'historique médical et les résultats des tests. La précision du diagnostic était de 98%.',
    'cases.case5.result': '98% de précision',
    'cases.case5.time': 'En 1 heure',
    'cases.case6.title': 'L\'agent voyage a trouvé la meilleure route',
    'cases.case6.desc': 'A trouvé l\'itinéraire de voyage optimal à travers 15 villes en 1 minute, en considérant le budget, les préférences, la météo et les événements locaux. A économisé 60% du budget original.',
    'cases.case6.result': '60% d\'économies budgétaires',
    'cases.case6.time': 'En 1 minute',
    'cases.case7.title': 'L\'agent éducatif a créé un cours',
    'cases.case7.desc': 'A créé un cours en ligne personnalisé qui a enseigné à 5 000 personnes en 2 mois. A adapté le matériel pour chaque étudiant, augmentant le taux de réussite de 70%.',
    'cases.case7.result': '5 000 étudiants',
    'cases.case7.time': 'En 2 mois',
    'cases.ready-success': 'Prêt à devenir le prochain cas de succès?',
    'cases.join-clients': 'Rejoignez des milliers de clients satisfaits qui utilisent déjà nos agents IA pour résoudre leurs tâches',
    'cases.more-details': 'Plus de Détails',
    
    // Services page
    'services.title': 'Nos Services',
    'services.subtitle': 'Choisissez l\'agent IA parfait pour vos tâches',
    'services.legal': 'Juridique',
    'services.legal.desc': 'Consultation juridique, analyse de documents, préparation de contrats',
    'services.marketing': 'Marketing',
    'services.marketing.desc': 'Promotion sur les réseaux sociaux, création de contenu, analyses',
    'services.logistics': 'Logistique',
    'services.logistics.desc': 'Optimisation des itinéraires, gestion d\'entrepôt, planification de livraison',
    'services.education': 'Éducation',
    'services.education.desc': 'Création de cours, tutorat, contenu éducatif',
    'services.medicine': 'Médecine',
    'services.medicine.desc': 'Assistance au diagnostic, surveillance de la santé, consultation médicale',
    'services.travel': 'Voyage',
    'services.travel.desc': 'Planification de voyages, réservations, optimisation d\'itinéraires',
    'services.productivity': 'Productivité',
    'services.productivity.desc': 'Automatisation des tâches, gestion des horaires, optimisation des flux de travail',
    'services.entertainment': 'Divertissement',
    'services.entertainment.desc': 'Création de contenu, développement de jeux, production médiatique',
    'services.finance': 'Finance',
    'services.finance.desc': 'Analyse financière, conseils d\'investissement, planification budgétaire',
    'services.construction': 'Construction',
    'services.construction.desc': 'Gestion de projets, estimation des coûts, contrôle qualité',
    'services.home': 'Assistant Domestique',
    'services.home.desc': 'Gestion de maison intelligente, tâches ménagères, assistance personnelle',
    'services.coaching': 'Coaching Personnel',
    'services.coaching.desc': 'Coaching de vie, développement des compétences, atteinte des objectifs',
    'services.order-form.title': 'Commander un Agent IA',
    'services.order-form.name': 'Nom',
    'services.order-form.email': 'Email',
    'services.order-form.service': 'Service',
    'services.order-form.description': 'Description de la Tâche',
    'services.order-form.select-service': 'Sélectionnez un service',
    'services.order-form.submit': 'Commander pour 2000 Cosmo',
    
    // Cosmo Token page
    'cosmo.title': 'Token Cosmo',
    'cosmo.subtitle': 'Votre clé vers les agents IA',
    'cosmo.description': 'Cosmo est le token principal de CosmoLab. C\'est votre clé vers les agents IA. Achetez Cosmo maintenant sur PancakeSwap au prix minimum et devenez partie du futur! Avec lui vous payez pour les agents, obtenez l\'accès au RWA et participez aux airdrops. Plus les gens achètent Cosmo, plus sa valeur augmente.',
    'cosmo.current-price': 'Prix Actuel',
    'cosmo.change-24h': 'Changement 24h',
    'cosmo.buy-pancakeswap': 'Acheter sur PancakeSwap',
    'cosmo.motivation': 'Le prix de départ c\'est maintenant - ne manquez pas votre chance!',
    'cosmo.benefits.title': 'Avantages du Token Cosmo',
    'cosmo.benefits.agents': 'Payer pour les agents IA',
    'cosmo.benefits.rwa': 'Accès au RWA',
    'cosmo.benefits.airdrops': 'Participer aux airdrops',
    'cosmo.benefits.growth': 'Croissance de la valeur du token',
    
    // Blog page
    'blog.title': 'Blog et Ressources',
    'blog.subtitle': 'Dernières nouvelles sur l\'IA et Cosmo',
    'blog.read-more': 'Lire Plus',
    
    // Contact page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Contactez notre équipe',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le Message',
    'contact.info': 'Informations de Contact',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Tableau de Bord',
    'dashboard.welcome': 'Bienvenue dans votre tableau de bord',
    'dashboard.agents': 'Mes Agents',
    'dashboard.tokens': 'Solde Cosmo',
    'dashboard.order-agent': 'Commander un Nouvel Agent',
    
    // Common buttons
    'btn.order-agent': 'Commander un Agent',
    'btn.buy-cosmo': 'Acheter Cosmo',
    'btn.learn-more': 'En Savoir Plus',
    'btn.send-message': 'Envoyer le Message',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'Demandez à CosmoAI',
    'chatbot.placeholder': 'Demandez sur les agents, tokens ou services...',
    'chatbot.send': 'Envoyer',
    
    // Footer
    'footer.description': 'Atelier d\'Agents Intelligents alimenté par CosmoAI. Créant des millions d\'agents IA pour résoudre toute tâche dans les affaires et la vie.',
    'footer.quick-links': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.copyright': '© CosmoLab 2025. Tous droits réservés.'
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.cases': 'Fälle',
    'nav.services': 'Dienstleistungen',
    'nav.cosmo-token': 'Cosmo Token',
    'nav.blog': 'Blog',
    'nav.contact': 'Kontakt',
    'nav.buy-cosmo': 'Cosmo kaufen',
    
    // Home page
    'home.title': 'CosmoLab: Werkstatt intelligenter Agenten',
    'home.subtitle': 'Löse jede Aufgabe mit Cosmo und Agenten',
    'home.our-agents': 'Unsere Agenten',
    'home.order-agent': 'Agent bestellen',
    'home.ready-future': 'Bereit für die Zukunft?',
    'home.join-revolution': 'Tritt jetzt der KI-Agenten-Revolution bei. Kaufe Cosmo-Token und erhalte Zugang zu Millionen intelligenten Assistenten.',
    
    // Agents
    'agent.lawyer': 'Anwalt',
    'agent.lawyer.desc': 'Analysiert Fälle, entwickelt Verteidigungsstrategien',
    'agent.home-assistant': 'Hausassistent',
    'agent.home-assistant.desc': 'Verwaltet Smart Home und persönliche Aufgaben',
    'agent.marketer': 'Vermarkter',
    'agent.marketer.desc': 'Erstellt Promotion-Strategien und Inhalte',
    'agent.medic': 'Mediziner',
    'agent.medic.desc': 'Hilft bei Diagnose und Behandlung',
    'agent.traveler': 'Reisender',
    'agent.traveler.desc': 'Plant perfekte Routen und Reisen',
    
    // About page
    '

about.title': 'Über CosmoLab',
    'about.workshop-future': 'Werkstatt der Zukunft',
    'about.description1': 'CosmoLab ist ein revolutionäres Projekt, das vom Haupt-KI-Meister CosmoAI für Automatisierung und Innovation in verschiedenen Bereichen menschlicher Aktivität geschaffen wurde.',
    'about.description2': 'Wir entwickeln Millionen intelligenter Roboter-Agenten, die 24/7 für Sie arbeiten und komplexe Aufgaben in Geschäft, Alltag, Recht, Marketing, Logistik, Bildung, Medizin und vielen anderen Bereichen lösen.',
    'about.ai-master': 'KI-Meister CosmoAI',
    'about.ai-master.desc': 'Die Haupt-KI, die alle Agenten erstellt und trainiert. CosmoAI verbessert ständig Algorithmen und erstellt neue Arten von Agenten zur Lösung einzigartiger Aufgaben.',
    'about.mission': 'Mission',
    'about.mission.desc': 'Wir schaffen ein Ökosystem intelligenter Agenten, das Menschen von Routineaufgaben befreit und ihnen ermöglicht, sich auf Kreativität und Entwicklung zu konzentrieren.',
    'about.why-cosmolab': 'Warum CosmoLab?',
    'about.speed': 'Geschwindigkeit',
    'about.speed.desc': 'Unsere Agenten arbeiten tausende Male schneller als Menschen',
    'about.accuracy': 'Genauigkeit',
    'about.accuracy.desc': 'Minimale Fehlerwahrscheinlichkeit dank KI',
    'about.savings': 'Einsparungen',
    'about.savings.desc': 'Erhebliche Reduzierung der Personalkosten',
    'about.tech-future': 'Zukunftstechnologien sind bereits hier',
    'about.tech-desc': 'CosmoLab nutzt fortschrittliche maschinelle Lerntechnologien, neuronale Netzwerke und Quantenalgorithmen, um die effizientesten KI-Agenten zu schaffen. Jeder Agent wird an Millionen von Beispielen trainiert und verbessert sich ständig.',
    
    // Cases page
    'cases.title': 'Erfolgsfälle',
    'cases.subtitle': 'Echte Ergebnisse unserer KI-Agenten, die bereits das Leben und die Geschäfte unserer Kunden verändert haben',
    'cases.case1.title': 'Anwalts-Agent sparte $250.000',
    'cases.case1.desc': 'Analysierte alle Richter- und Geschworenenfälle, entwickelte Strategie, Fall wurde wegen fehlender Straftat geschlossen. KI-Anwalts-Agent kostete den Kunden nur $2.000.',
    'cases.case1.result': '$250.000 Ersparnis',
    'cases.case1.time': 'In 48 Stunden',
    'cases.case2.title': 'Marketing-Agent verdreifachte Verkäufe',
    'cases.case2.desc': 'Verdreifachte Verkäufe in einem Monat und halbierte Marketing-Budgets durch Automatisierung von Social-Media-Posts, Analysen und ständige Inhaltsverbesserung.',
    'cases.case2.result': '300% Verkaufswachstum',
    'cases.case2.time': 'In 1 Monat',
    'cases.case3.title': 'Logistik-Agent sparte eine Million',
    'cases.case3.desc': 'Optimierte Lieferwege, reduzierte Reisezeit um 40% und senkte Kraftstoffkosten. Automatisierte Planung und Versanddienst.',
    'cases.case3.result': '$1.000.000 Ersparnis',
    'cases.case3.time': 'In 3 Monaten',
    'cases.case4.title': 'Support-Agent bearbeitete 10.000 Anfragen',
    'cases.case4.desc': 'Bearbeitete 10.000 unbearbeitete Kundenanfragen in einer Woche, erhöhte Kundenzufriedenheit um 85% und reduzierte Antwortzeit auf 30 Sekunden.',
    'cases.case4.result': '10.000 Anfragen',
    'cases.case4.time': 'In 1 Woche',
    'cases.case5.title': 'Medizinischer Agent half bei Diagnose',
    'cases.case5.desc': 'Half bei der Diagnose einer seltenen Krankheit in einer Stunde durch Analyse von Symptomen, Krankengeschichte und Testergebnissen. Diagnosegenauigkeit betrug 98%.',
    'cases.case5.result': '98% Genauigkeit',
    'cases.case5.time': 'In 1 Stunde',
    'cases.case6.title': 'Reise-Agent fand beste Route',
    'cases.case6.desc': 'Fand optimale Reiseroute durch 15 Städte in 1 Minute unter Berücksichtigung von Budget, Präferenzen, Wetter und lokalen Veranstaltungen. Sparte 60% des ursprünglichen Budgets.',
    'cases.case6.result': '60% Budgetersparnis',
    'cases.case6.time': 'In 1 Minute',
    'cases.case7.title': 'Bildungs-Agent erstellte Kurs',
    'cases.case7.desc': 'Erstellte personalisierten Online-Kurs, der 5.000 Menschen in 2 Monaten unterrichtete. Passte Material für jeden Schüler an, erhöhte Erfolgsrate um 70%.',
    'cases.case7.result': '5.000 Schüler',
    'cases.case7.time': 'In 2 Monaten',
    'cases.ready-success': 'Bereit, der nächste Erfolgsfall zu werden?',
    'cases.join-clients': 'Schließe dich tausenden zufriedenen Kunden an, die bereits unsere KI-Agenten zur Lösung ihrer Aufgaben nutzen',
    'cases.more-details': 'Mehr Details',
    
    // Services page
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Wähle den perfekten KI-Agenten für deine Aufgaben',
    'services.legal': 'Rechtlich',
    'services.legal.desc': 'Rechtsberatung, Dokumentenanalyse, Vertragsvorbereitung',
    'services.marketing': 'Marketing',
    'services.marketing.desc': 'Social-Media-Promotion, Content-Erstellung, Analysen',
    'services.logistics': 'Logistik',
    'services.logistics.desc': 'Routenoptimierung, Lagerverwaltung, Lieferplanung',
    'services.education': 'Bildung',
    'services.education.desc': 'Kurserstellung, Nachhilfe, Bildungsinhalte',
    'services.medicine': 'Medizin',
    'services.medicine.desc': 'Diagnosehilfe, Gesundheitsüberwachung, medizinische Beratung',
    'services.travel': 'Reisen',
    'services.travel.desc': 'Reiseplanung, Buchungen, Routenoptimierung',
    'services.productivity': 'Produktivität',
    'services.productivity.desc': 'Aufgabenautomatisierung, Terminverwaltung, Workflow-Optimierung',
    'services.entertainment': 'Unterhaltung',
    'services.entertainment.desc': 'Content-Erstellung, Spieleentwicklung, Medienproduktion',
    'services.finance': 'Finanzen',
    'services.finance.desc': 'Finanzanalyse, Investmentberatung, Budgetplanung',
    'services.construction': 'Bauwesen',
    'services.construction.desc': 'Projektmanagement, Kostenschätzung, Qualitätskontrolle',
    'services.home': 'Hausassistent',
    'services.home.desc': 'Smart-Home-Verwaltung, Haushaltsaufgaben, persönliche Assistenz',
    'services.coaching': 'Personal Coaching',
    'services.coaching.desc': 'Life-Coaching, Kompetenzentwicklung, Zielerreichung',
    'services.order-form.title': 'KI-Agent bestellen',
    'services.order-form.name': 'Name',
    'services.order-form.email': 'E-Mail',
    'services.order-form.service': 'Service',
    'services.order-form.description': 'Aufgabenbeschreibung',
    'services.order-form.select-service': 'Service auswählen',
    'services.order-form.submit': 'Für 2000 Cosmo bestellen',
    
    // Cosmo Token page
    'cosmo.title': 'Cosmo Token',
    'cosmo.subtitle': 'Dein Schlüssel zu KI-Agenten',
    'cosmo.description': 'Cosmo ist das Haupt-Token von CosmoLab. Das ist dein Schlüssel zu KI-Agenten. Kaufe Cosmo jetzt auf PancakeSwap zum Mindestpreis und werde Teil der Zukunft! Damit bezahlst du für Agenten, erhältst Zugang zu RWA und nimmst an Airdrops teil. Je mehr Menschen Cosmo kaufen, desto höher wird sein Wert.',
    'cosmo.current-price': 'Aktueller Preis',
    'cosmo.change-24h': '24h Änderung',
    'cosmo.buy-pancakeswap': 'Auf PancakeSwap kaufen',
    'cosmo.motivation': 'Der Startpreis ist jetzt - verpasse deine Chance nicht!',
    'cosmo.benefits.title': 'Vorteile des Cosmo Tokens',
    'cosmo.benefits.agents': 'Für KI-Agenten bezahlen',
    'cosmo.benefits.rwa': 'Zugang zu RWA',
    'cosmo.benefits.airdrops': 'An Airdrops teilnehmen',
    'cosmo.benefits.growth': 'Token-Wertsteigerung',
    
    // Blog page
    'blog.title': 'Blog und Ressourcen',
    'blog.subtitle': 'Neueste Nachrichten über KI und Cosmo',
    'blog.read-more': 'Mehr lesen',
    
    // Contact page
    'contact.title': 'Kontaktiere uns',
    'contact.subtitle': 'Kontaktiere unser Team',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'contact.info': 'Kontaktinformationen',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Willkommen in deinem Dashboard',
    'dashboard.agents': 'Meine Agenten',
    'dashboard.tokens': 'Cosmo Guthaben',
    'dashboard.order-agent': 'Neuen Agent bestellen',
    
    // Common buttons
    'btn.order-agent': 'Agent bestellen',
    'btn.buy-cosmo': 'Cosmo kaufen',
    'btn.learn-more': 'Mehr erfahren',
    'btn.send-message': 'Nachricht senden',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'CosmoAI fragen',
    'chatbot.placeholder': 'Frage nach Agenten, Token oder Services...',
    'chatbot.send': 'Senden',
    
    // Footer
    'footer.description': 'Werkstatt intelligenter Agenten powered by CosmoAI. Erschaffung von Millionen KI-Agenten zur Lösung jeder Aufgabe in Geschäft und Leben.',
    'footer.quick-links': 'Schnelllinks',
    'footer.contact': 'Kontakt',
    'footer.copyright': '© CosmoLab 2025. Alle Rechte vorbehalten.'
  },
  ja: {
    // Navigation
    'nav.home': 'ホーム',
    'nav.about': '私たちについて',
    'nav.cases': 'ケース',
    'nav.services': 'サービス',
    'nav.cosmo-token': 'Cosmoトークン',
    'nav.blog': 'ブログ',
    'nav.contact': 'お問い合わせ',
    'nav.buy-cosmo': 'Cosmoを購入',
    
    // Home page
    'home.title': 'CosmoLab：スマートエージェントの工房',
    'home.subtitle': 'Cosmoとエージェントであらゆるタスクを解決',
    'home.our-agents': '私たちのエージェント',
    'home.order-agent': 'エージェントを注文',
    'home.ready-future': '未来の準備はできていますか？',
    'home.join-revolution': '今すぐAIエージェント革命に参加しましょう。Cosmoトークンを購入して、何百万ものスマートアシスタントにアクセスできます。',
    
    // Agents
    'agent.lawyer': '弁護士',
    'agent.lawyer.desc': '事件を分析し、防御戦略を開発',
    'agent.home-assistant': 'ホームアシスタント',
    'agent.home-assistant.desc': 'スマートホームと個人タスクを管理',
    'agent.marketer': 'マーケター',
    'agent.marketer.desc': 'プロモーション戦略とコンテンツを作成',
    'agent.medic': '医師',
    'agent.medic.desc': '診断と治療を支援',
    'agent.traveler': '旅行者',
    'agent.traveler.desc': '完璧なルートと旅行を計画',
    
    // About page
    'about.title': 'CosmoLabについて',
    'about.workshop-future': '未来の工房',
    'about.description1': 'CosmoLabは、人間活動のさまざまな分野での自動化と革新のために主要な人工知能マスターCosmoAIによって作成された革新的なプロジェクトです。',
    'about.description2': '私たちは24時間年中無休であなたのために働き、ビジネス、日常生活、法律、マーケティング、物流、教育、医学などの多くの分野で複雑なタスクを解決する何百万ものスマートロボットエージェントを開発しています。',
    'about.ai-master': 'AIマスターCosmoAI',
    'about.ai-master.desc': 'すべてのエージェントを作成し訓練する主要な人工知能。CosmoAIは常にアルゴリズムを改善し、ユニークなタスクを解決するために新しいタイプのエージェントを作成します。',
    'about.mission': 'ミッション',
    'about.mission.desc': '私たちは、人々を日常的なタスクから解放し、創造性と開発に集中できるようにするスマートエージェントのエコシステムを作成します。',
    'about.why-cosmolab': 'なぜCosmoLabなのか？',
    'about.speed': 'スピード',
    'about.speed.desc': '私たちのエージェントは人間の数千倍の速度で働きます',
    'about.accuracy': '精度',
    'about.accuracy.desc': 'AIのおかげで最小限のエラー確率',
    'about.savings': '節約',
    'about.savings.desc': '人件費の大幅な削減',
    'about.tech-future': '未来のテクノロジーがすでにここにあります',
    'about.tech-desc': 'CosmoLabは、最も効率的なAIエージェントを作成するために、高度な機械学習技術、ニューラルネットワーク、量子アルゴリズムを使用しています。各エージェントは何百万もの例で訓練され、常に改善されています。',
    
    // Cases page
    'cases.title': '成功事例',
    'cases.subtitle': 'すでにクライアントの生活とビジネスを変えた私たちのAIエージェントの実際の結果',
    'cases.case1.title': '弁護士エージェントが$250,000を節約',
    'cases.case1.desc': 'すべての裁判官と陪審員の事件を分析し、戦略を開発、犯罪不成立により事件が終了。AI弁護士エージェントはクライアントに$2,000しかかかりませんでした。',
    'cases.case1.result': '$250,000の節約',
    'cases.case1.time': '48時間で',
    'cases.case2.title': 'マーケティングエージェントが売上を3倍に',
    'cases.case2.desc': 'ソーシャルメディア投稿の自動化、分析、コンテンツの継続的改善により、1ヶ月で売上を3倍にし、マーケティング予算を半分にしました。',
    'cases.case2.result': '300%の売上成長',
    'cases.case2.time': '1ヶ月で',
    'cases.case3.title': '物流エージェントが100万ドルを節約',
    'cases.case3.desc': '配送ルートを最適化し、移動時間を40%短縮し、燃料費を削減。計画と配送サービスを自動化しました。',
    'cases.case3.result': '$1,000,000の節約',
    'cases.case3.time': '3ヶ月で',
    'cases.case4.title': 'サポートエージェントが10,000件のリクエストを処理',
    'cases.case4.desc': '1週間で10,000件の未処理の顧客リクエストを処理し、顧客満足度を85%向上させ、応答時間を30秒に短縮しました。',
    'cases.case4.result': '10,000件のリクエスト',
    'cases.case4.time': '1週間で',
    'cases.case5.title': '医療エージェントが診断を支援',
    'cases.case5.desc': '症状、病歴、検査結果を分析して、1時間で稀な病気の診断を支援しました。診断精度は98%でした。',
    'cases.case5.result': '98%の精度',
    'cases.case5.time': '1時間で',
    'cases.case6.title': '旅行エージェントが最適なルートを発見',
    'cases.case6.desc': '予算、好み、天気、地元のイベントを考慮して、1分で15都市を通る最適な旅行ルートを見つけました。元の予算の60%を節約しました。',
    'cases.case6.result': '60%の予算節約',
    'cases.case6.time': '1分で',
    'cases.case7.title': '教育エージェントがコースを作成',
    'cases.case7.desc': '2ヶ月で5,000人に教えるパーソナライズされたオンラインコースを作成しました。各学生に合わせて教材を適応させ、成功率を70%向上させました。',
    'cases.case7.result': '5,000人の学生',
    'cases.case7.time': '2ヶ月で',
    'cases.ready-success': '次の成功事例になる準備はできていますか？',
    'cases.join-clients': 'すでに私たちのAIエージェントを使用してタスクを解決している何千もの満足したクライアントに参加してください',
    'cases.more-details': '詳細',
    
    // Services page
    'services.title': '私たちのサービス',
    'services.subtitle': 'あなたのタスクに最適なAIエージェントを選択してください',
    'services.legal': '法務',
    'services.legal.desc': '法的相談、文書分析、契約準備',
    'services.marketing': 'マーケティング',
    'services.marketing.desc': 'ソーシャルメディアプロモーション、コンテンツ作成、アナリティクス',
    'services.logistics': '物流',
    'services.logistics.desc': 'ルート最適化、倉庫管理、配送計画',
    'services.education': '教育',
    'services.education.desc': 'コース作成、個別指導、教育コンテンツ',
    'services.medicine': '医療',
    'services.medicine.desc': '診断支援、健康監視、医療相談',
    'services.travel': '旅行',
    'services.travel.desc': '旅行計画、予約、ルート最適化',
    'services.productivity': '生産性',
    'services.productivity.desc': 'タスク自動化、スケジュール管理、ワークフロー最適化',
    'services.entertainment': 'エンターテイメント',
    'services.entertainment.desc': 'コンテンツ作成、ゲーム開発、メディア制作',
    'services.finance': '金融',
    'services.finance.desc': '財務分析、投資アドバイス、予算計画',
    'services.construction': '建設',
    'services.construction.desc': 'プロジェクト管理、コスト見積もり、品質管理',
    'services.home': 'ホームアシスタント',
    'services.home.desc': 'スマートホーム管理、家事、個人アシスタンス',
    'services.coaching': 'パーソナルコーチング',
    'services.coaching.desc': 'ライフコーチング、スキル開発、目標達成',
    'services.order-form.title': 'AIエージェントを注文',
    'services.order-form.name': '名前',
    'services.order-form.email': 'メール',
    'services.order-form.service': 'サービス',
    'services.order-form.description': 'タスクの説明',
    'services.order-form.select-service': 'サービスを選択',
    'services.order-form.submit': '2000 Cosmoで注文',
    
    // Cosmo Token page
    'cosmo.title': 'Cosmoトークン',
    'cosmo.subtitle': 'AIエージェントへのあなたの鍵',
    'cosmo.description': 'CosmoはCosmoLabのメイントークンです。これはAIエージェントへのあなたの鍵です。今すぐPancakeSwapで最低価格でCosmoを購入し、未来の一部になりましょう！これでエージェントの料金を支払い、RWAへのアクセスを得て、エアドロップに参加できます。Cosmoを購入する人が多いほど、その価値は高くなります。',
    'cosmo.current-price': '現在価格',
    'cosmo.change-24h': '24時間変動',
    'cosmo.buy-pancakeswap': 'PancakeSwapで購入',
    'cosmo.motivation': '開始価格は今です - チャンスを逃さないでください！',
    'cosmo.benefits.title': 'Cosmoトークンの利点',
    'cosmo.benefits.agents': 'AIエージェントの支払い',
    'cosmo.benefits.rwa': 'RWAへのアクセス',
    'cosmo.benefits.airdrops': 'エアドロップへの参加',
    'cosmo.benefits.growth': 'トークン価値の成長',
    
    // Blog page
    'blog.title': 'ブログとリソース',
    'blog.subtitle': 'AIとCosmoに関する最新ニュース',
    'blog.read-more': '続きを読む',
    
    // Contact page
    'contact.title': 'お問い合わせ',
    'contact.subtitle': '私たちのチームに連絡してください',
    'contact.name': '名前',
    'contact.email': 'メール',
    'contact.message': 'メッセージ',
    'contact.send': 'メッセージを送信',
    'contact.info': '連絡先情報',
    'contact.support-email': 'support@cosmolab.space',
    
    // Dashboard
    'dashboard.title': 'ダッシュボード',
    'dashboard.welcome': 'ダッシュボードへようこそ',
    'dashboard.agents': '私のエージェント',
    'dashboard.tokens': 'Cosmo残高',
    'dashboard.order-agent': '新しいエージェントを注文',
    
    // Common buttons
    'btn.order-agent': 'エージェントを注文',
    'btn.buy-cosmo': 'Cosmoを購入',
    'btn.learn-more': '詳細を見る',
    'btn.send-message': 'メッセージを送信',
    
    // ChatBot
    'chatbot.ask-cosmoai': 'CosmoAIに質問',
    'chatbot.placeholder': 'エージェント、トークン、サービスについて質問...',
    'chatbot.send': '送信',
    
    // Footer
    'footer.description': 'CosmoAIによって動かされるスマートエージェントの工房。ビジネスと生活のあらゆるタスクを解決するために何百万ものAIエージェントを作成しています。',
    'footer.quick-links': 'クイックリンク',
    'footer.contact': '連絡先',
    'footer.copyright': '© CosmoLab 2025. 全権利留保。'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'ru', 'es', 'zh', 'hi', 'ar', 'pt', 'fr', 'de', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLang

uage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
