// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vywyvurpxjyqvlsmcsub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5d3l2dXJweGp5cXZsc21jc3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjYxNzMsImV4cCI6MjA2NjAwMjE3M30.ZcVeHGrZhfHteDRCX2UEliZujvEWlH2I2Ogu1fea5uQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);